### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by rafw** [adshao/go-binance#1]
Error occurs in NewAggTradesService.

OS: mac os 10.11
Go: 1.9

**Comment by adshao** [comment]
Hi rafw,
Could you give more info about this issue? the code snippet, output, etc.

**Comment by rafw** [comment]
`package main

import (
	"github.com/adshao/go-binance"
	"fmt"
	"context"
)

func main() {
	client := binance.NewClient("", "")
	trades, err := client.NewAggTradesService().
		Symbol("LTCBTC").StartTime(1508673256594).EndTime(1508673256595).
		Do(context.Background())
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, t := range trades {
		fmt.Println(t)
	}
}`

**Comment by rafw** [comment]
Just the sample code. And I removed access key and secret key in the demo.

**Comment by adshao** [comment]
seems like a certificate issue on your server, can you try to update your ca bundle? if you are using CentOS, try this: `sudo yum reinstall ca-certificates`
I guess it is casued by the changing of binance ssl certificate recently.

**Comment by rafw** [comment]
哎呀妈呀，我用的是macOs 10.11，同样的代码放在ubuntu上就对了。究竟咋回事呢，老闹心了。

**Comment by adshao** [comment]
请问你的Go版本是什么？根据你提供的几个链接，升级到Go1.9是否还存在这个问题？

**Comment by rafw** [comment]
从1.7升级到1.9，还是一样的，按外国论坛的说法是因为mac 10.10、10.11导致的，升级操作系统可以解决

**Comment by adshao** [comment]
我在OSX 10.12上没有遇到这个问题，看样子是跟本地环境有关。有几个方法可以确认是否是OSX上Go的问题:

1. 本地执行`curl https://www.binance.com/api/v1/aggTrades?endTime=1508673256595&startTime=1508673256594&symbol=LTCBTC` 是否正常
2. 本地使用Go访问其他https站点，或者使用另外的go binance SDK访问看看是否有同样的问题

**Comment by rafw** [comment]
1、curl https://www.binance.com/api/v1/aggTrades?symbol=LTCBTC 返回正常

**Comment by adshao** [comment]
Hi,
从测试结果来看，可以定位为环境问题，两种可能：
1. OSX Go的问题，在验证HTTPS证书时找的CA证书不对
2. 环境CA证书有问题
对于OSX环境的这个错误，我只看到go源码的这个文件出现，如果想排查可以根据源码看看哪里有问题：https://github.com/golang/go/blob/release-branch.go1.9/src/crypto/x509/verify.go#L405
如果无法解决，或者也可以先用Insecure方式绕过，等部署到其他环境时再去掉。

**Comment by rafw** [comment]
嗯，等过段时间10.13稳定版出了，我升级后再试。程序最终也是linux、windows下跑，我更担心是mac不安全导致的。

**Comment by adshao** [comment]
ok，如果解决了，麻烦告知解决办法。

**Comment by rafw** [comment]
🆗
