### ISSUE TITLE
[Feature Request] support Side Effect Type when placing margin order

### ISSUE THREAD

**Issue by Krisa** [adshao/go-binance#100]
It looks like we can place finally (useful) margin orders through the API when setting `sideEffectType` to `MARGIN_BUY` according to the Change Log from Nov 30th: https://binance-docs.github.io/apidocs/spot/en/#change-log. 

It would be nice if it was added to the code of this package.

**Comment by adshao** [comment]
Hi @Krisa , thanks for the info, this has been implemented in pr #101 , let me know if there is any problem.
