### ISSUE TITLE
Error -1106 randomly occurring

### ISSUE THREAD

**Issue by georgk10** [adshao/go-binance#105]
I'm not sure whether it's a problem regarding this SDK or if it's a problem with Binance (because I'm creating orders quickly one after the other - around 20ms between two orders). 
Sometimes (like 50% of the time)  the following error occurs when my bot tries to place an order:
> <APIError> code=-1106, msg=Parameter 'quantity' sent when not required.

I cannot see why the error occurs, it just seems to be random. I'm using the client to create market orders as quoted below. :

`func order(market, side, amount string){
    if side == "buy"{
        _, err := client.NewCreateOrderService().Symbol(market).
            Side(binance.SideTypeBuy).Type(binance.OrderTypeMarket).
            Quantity(amount).
            Do(context.Background())
        if err != nil{
			fmt.Println(err)
        }     
    }
    if side == "sell" {
        _, err := client.NewCreateOrderService().Symbol(market).
            Side(binance.SideTypeSell).Type(binance.OrderTypeMarket).
            Quantity(amount).
            Do(context.Background())
        if err != nil{
			fmt.Println(err)
        }     
    }
}`

**Comment by adshao** [comment]
hi @georgk10 , could you set `client.Debug = true` to print the request info?
I'm not sure the restriction of Market order, however, it would be better to ask admins in [binance API telegram group](https://t.me/binance_api_english) about the error.

**Comment by georgk10** [comment]
Hi @adshao , here is the output generated by my bot with client.debug = true:

> Binance-golang 2020/01/16 18:06:01 response: &http.Response{Status:"400 Bad Request", StatusCode:400, Proto:"HTTP/2.0", ProtoMajor:2, ProtoMinor:0, Header:http.Header{"Date":[]string{"Thu, 16 Jan 2020 18:06:01 GMT"}, "Server":[]string{"nginx"}, "X-Mbx-Uuid":[]string{"2b5088c2-b8fc-4f76-88f2-b906c5d71414"}, "X-Cache":[]string{"Error from cloudfront"}, "Via":[]string{"1.1 5e2b2bef8be6bee05fe23de3ed9e3a6e.cloudfront.net (CloudFront)"}, "X-Amz-Cf-Id":[]string{"Q0sqHtThGAz-v_8eXU8a12w1YaWNt4leF4DWNTSi0DjSoL35Augwhw=="}, "X-Mbx-Used-Weight-1m":[]string{"6"}, "X-Content-Type-Options":[]string{"nosniff"}, "Content-Security-Policy":[]string{"default-src 'self'"}, "Pragma":[]string{"no-cache"}, "X-Amz-Cf-Pop":[]string{"DUB2-C1"}, "X-Mbx-Used-Weight":[]string{"6"}, "Strict-Transport-Security":[]string{"max-age=31536000; includeSubdomains"}, "X-Content-Security-Policy":[]string{"default-src 'self'"}, "X-Webkit-Csp":[]string{"default-src 'self'"}, "Expires":[]string{"0"}, "Content-Type":[]string{"application/json;charset=utf-8"}, "X-Frame-Options":[]string{"SAMEORIGIN"}, "X-Xss-Protection":[]string{"1; mode=block"}, "Cache-Control":[]string{"no-cache, no-store, must-revalidate"}}, Body:http.http2transportResponseBody{cs:(*http.http2clientStream)(0xc4203d6140)}, ContentLength:-1, TransferEncoding:[]string(nil), Close:false, Uncompressed:false, Trailer:http.Header(nil), Request:(*http.Request)(0xc4200ec400), TLS:(*tls.ConnectionState)(0xc4203cc790)}
Binance-golang 2020/01/16 18:06:01 response body: {"code":-1106,"msg":"Parameter 'quantity' sent when not required."}
Binance-golang 2020/01/16 18:06:01 response status code: 400
<APIError> code=-1106, msg=Parameter 'quantity' sent when not required.

**Comment by georgk10** [comment]
Problem solved, the log showed that quantity was set to 0 due to an calculation problem. Everything works fine now. Thanks for the hint with setting client.debug = true

**Comment by adshao** [comment]
> Problem solved, the log showed that quantity was set to 0 due to an calculation problem. Everything works fine now. Thanks for the hint with setting client.debug = true

Glad to hear that.
