### ISSUE TITLE
Not able to close WsUserDataServe by using only `stopC`

### ISSUE THREAD

**Issue by friday-james** [adshao/go-binance#107]
I used the same way as mentioned on `README.md` to close the websocket. It does close `WsDepthServe`, but doesn't close `WsUserServe` until I have placed an order to trigger the `wsHandler`.

```
wsHandler := func(message []byte) {
	fmt.Println(string(message))
}
errHandler := func(err error) {
	fmt.Println(err)
}
doneC, stopC, err := binance.WsUserDataServe(listenKey, wsHandler, errHandler)
if err != nil {
	fmt.Println(err)
	return
}
// use stopC to exit
go func() {
	time.Sleep(5 * time.Second)
	stopC <- struct{}{}
}()
<-doneC
```

**Comment by halink0803** [comment]
It seems like you got the WsUserDataServe to work? How can you get the listenKey for it? I take a look at the StartUserStreamService but it does not implemented the New function :-/

**Comment by halink0803** [comment]
Nevermind, I miss read the part of creating NewStartUserStreamService, it works fine.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
