### ISSUE TITLE
Keep synced with Binance Server Time or allow a time offset to be set

### ISSUE THREAD

**Issue by Krisa** [adshao/go-binance#127]
follow-up on https://github.com/adshao/go-binance/pull/125

It's sometimes hard (require external sync application), or not possible, and at best requires lots of tooling to be able to change the time machine, especially in cross environment (Windows, Linux, Darwin)... And in case one needs the require permissions to run such tools and do such modifications.

I see for example that the most popular Binance JS library is having such feature https://github.com/jaggedsoft/node-binance-api#troubleshooting. By making a call to that method, it sets an internal flag timeOffset https://github.com/jaggedsoft/node-binance-api/blob/d011f5845a91c06a0f4ef32ff08bed31d53cb29e/node-binance-api.js#L1207 used in subsequent signed requests here https://github.com/jaggedsoft/node-binance-api/blob/d011f5845a91c06a0f4ef32ff08bed31d53cb29e/node-binance-api.js#L192

I would have preferred myself go-binance to analyse the error code -1021 somewhere in the central callAPI method (https://github.com/adshao/go-binance/blob/master/client.go#L244) and in such case get the Binance time, set an internal offset and re-do the request. After all this library does not give a way to centralise errors from all different methods and so we don't have a good way to do that as of now.

Either way, I think that what is done in node-binance is at least a very acceptable trade-off which one could use in a hourly or daily cron job to ensure that the time is always quite accurate

**Comment by Krisa** [comment]
@adshao thoughts ?

**Comment by adshao** [comment]
@Krisa Sorry for the late reply. Yes, I agree with you, an optional parameter `useServerTime` in https://github.com/jaggedsoft/node-binance-api#troubleshooting is more acceptable and useful in some cases than directly calling ntp synchronization in  #125.

**Comment by adshao** [comment]
To support this feature, we could set `useServerTime` in  https://github.com/adshao/go-binance/blob/master/client.go#L191 as a per request option.

**Comment by Krisa** [comment]
@adshao The problem of `useServerTime` in the node binance library is that it does a one time request when the client is initialized and... that's it. If the app is running multiple days, we can easily get out of sync again. That's the opposite of #125, and not really better either. 

I'd be more in favour of exposing the `timeOffset` here https://github.com/jaggedsoft/node-binance-api/blob/d011f5845a91c06a0f4ef32ff08bed31d53cb29e/node-binance-api.js#L1207 (or rather `TimeOffset`) in the Client https://github.com/adshao/go-binance/blob/master/client.go#L172 which can be overwritten. A function `BinanceClient.NewSetTimeOffsetService().Do(context.Background())` could also accessory set this TimeOffset, but that would be nothing more than querying Binance time and putting it TimeOffset. Actually node-binance is also having such function here https://github.com/jaggedsoft/node-binance-api/blob/d011f5845a91c06a0f4ef32ff08bed31d53cb29e/node-binance-api.js#L1979 (additionally to the init param)
