### ISSUE TITLE
Semantic Versioning in Go

### ISSUE THREAD

**Issue by hiroaki-yamamoto** [adshao/go-binance#138]
Hi,

I think this topic is what you might know, but as fyi, all go package release should be prefixed with "v" (e.g. v1.0.0, v1.1.0, v2.0.0...) so that go mod can find the version ([Check this](https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning)).

Also, I like your binance package better than official api code :smile:

**Comment by adshao** [comment]
thanks @hiroaki-yamamoto , just added tag [v2.1.1](https://github.com/adshao/go-binance/tree/v2.1.1), let me know if there is any problem.
