### ISSUE TITLE
how to register to the Diff. Depth Stream 

### ISSUE THREAD

**Issue by im4kv** [adshao/go-binance#140]
Hi all,
Is there any documentation that describe how to subscribe to the Diff. Depth Stream to locally keep an order book?

Thanks in advance

**Comment by adshao** [comment]
Hi @ikhosravi , please refer to: https://binance-docs.github.io/apidocs/spot/en/#diff-depth-stream

### How to manage a local order book correctly

1. Open a stream to wss://stream.binance.com:9443/ws/bnbbtc@depth.
1. Buffer the events you receive from the stream.
1. Get a depth snapshot from https://www.binance.com/api/v3/depth?symbol=BNBBTC&limit=1000 .
1. Drop any event where u is <= lastUpdateId in the snapshot.
1. The first processed event should have U <= lastUpdateId+1 AND u >= lastUpdateId+1.
1. While listening to the stream, each new event's U should be equal to the previous event's u+1.
1. The data in each event is the absolute quantity for a price level.
1. If the quantity is 0, remove the price level.
1. Receiving an event that removes a price level that is not in your local order book can happen and is normal.

**Comment by adshao** [comment]
The websocket usage is described [here](https://github.com/adshao/go-binance#depth).

**Comment by ikhosravi** [comment]
thanks @adshao I've already seen the doc but I thought maybe there is some sort of implemented function related to this functionality into Go-binance package. do you suggest to do the instruction of the doc using go-binance or use ordinary WebSocket client to do it?

**Comment by ikhosravi** [comment]
Got it

> The websocket usage is described [here](https://github.com/adshao/go-binance#depth).

Got it, but I should do the REST call separately right?
and how could I set the depth of requested orderbook? I mean: bnbbtc@depth

**Comment by adshao** [comment]
> > The websocket usage is described [here](https://github.com/adshao/go-binance#depth).
> 
> Thanks, but I should do the REST call separately right?
> and how could I set the depth of requested orderbook? I mean: bnbbtc@depth

Yes, REST API should be called separately from websocket.
I think you should manually update the bids and asks to keep a newest order book. For the implementation of local order book, I suggest discussing this topic in binance [official telegram group](https://t.me/binance_api.english).

**Comment by xyq-c-cpp** [comment]
completed, close this.
