### ISSUE TITLE
Options API (aka Delivery)

### ISSUE THREAD

**Issue by 0cv** [adshao/go-binance#145]
Options trading is going to be a thing when it comes to Desktop (only available on Mobile atm). @adshao do you have plans to implement it, or anyone else in the near future? 

for reference https://binance-docs.github.io/apidocs/delivery/en/#change-log

**Comment by adshao** [comment]
Hi @Krisa , seems like a big feature, I'll have a look at it. BTW, are you interested in implementing it?

**Comment by Krisa** [comment]
@adshao - well I was more interested in using it 🤣  This being said, yeah it's again a brand new API, but on the brighter side, it's almost a perfect clone from the Future API. Duplicating the Future API, replacing fapi, by dapi and then some small changes here and there and we should be good to a large extent.

**Comment by adshao** [comment]
> @adshao - well I was more interested in using it 🤣 This being said, yeah it's again a brand new API, but on the brighter side, it's almost a perfect clone from the Future API. Duplicating the Future API, replacing fapi, by dapi and then some small changes here and there and we should be good to a large extent.

Yes, it's just another Future API. Thanks for the suggestion, hopefully I'll implement it in a few weeks :)
