### ISSUE TITLE
WsDepthEvent is only available for Spot Market

### ISSUE THREAD

**Issue by siaminator** [adshao/go-binance#149]
There are a series of WebSocket APIs that are available for future market independently from the spot market and have different data. One of which would be `binance.WsDepthEvent`:
currently the implementation is using `baseURL` to access this websocket which is for the spot market. so I could not find a way to use this library to listen to `Futures Diff. Book Depth Streams`.

This would mean for example I can not use this library to run the binance instructions for running a local copy of the `order book`, since I am able to take the snap shot correctly for the future market using `futures.DepthService`, but have not way to listen to **Futures** Diff ticks:

### How to manage a local order book correctly
1. Open a stream to wss://fstream.binance.com/stream?streams=btcusdt@depth.
2. Buffer the events you receive from the stream. For same price, latest received update covers the previous one.
3. Get a depth snapshot from https://fapi.binance.com/fapi/v1/depth?symbol=BTCUSDT&limit=1000 .
4. Drop any event where u is < lastUpdateId in the snapshot.
5. The first processed event should have U <= lastUpdateId AND u >= lastUpdateId
6. While listening to the stream, each new event's pu should be equal to the previous event's u, otherwise initialize the process from step 3.
7. The data in each event is the absolute quantity for a price level.
8. If the quantity is 0, remove the price level.
9. Receiving an event that removes a price level that is not in your local order book can happen and is normal.

**Comment by siaminator** [comment]
We need either a type of market for the input of this method based on which to decide which Base to use, or 2 different methods, maybe even separate the package for `Futures` wss APIs, same way it has been done for the REST ones

**Comment by adshao** [comment]
> We need either a type of market for the input of this method based on which to decide which Base to use, or 2 different methods, maybe even separate the package for `Futures` wss APIs, same way it has been done for the REST ones

Hi @siaminator , you are right, we need to add separate websocket APIs to `futures` package. I'll working on this next week.

**Comment by afenrir** [comment]
Hey @adshao, thanks for this awesome library. I wonder if you have had an opportunity to make any progress with the futures websocket endpoints? If not, do you know of any workarounds?
