### ISSUE TITLE
Futures support

### ISSUE THREAD

**Issue by i0x71** [adshao/go-binance#150]
Hi,
Is there a list or supported features for futures trading ?

Thanks

**Comment by adshao** [comment]
> Hi,
> Is there a list or supported features for futures trading ?
> 
> Thanks

Not yet, if you find any features missing, feel free to submit a pull request or open an issue for it.

**Comment by javierjait** [comment]
Hi, can I use coin-futures with futures client (https://dapi.binance.com)?

Thanks

**Comment by adshao** [comment]
> Hi, can I use coin-futures with futures client (https://dapi.binance.com)?
> 
> Thanks

It's not implemented yet.

**Comment by xyq-c-cpp** [comment]
completed, close this.
