### ISSUE TITLE
WsFutureUserDataServe regular disconnects 

### ISSUE THREAD

**Issue by adampointer** [adshao/go-binance#151]
Hi,

The user data stream on the futures api disconnects a lot. It is inconsistent. Sometimes it is every 5-10 minutes other times it can be stable for hours. It could well be an issue with Binance or my software. My bot works perfectly on the spot api which is weird. 

Do you experience this too or is it just me?

**Comment by Krisa** [comment]
Now you're writing about this, I checked my logs and ... 😱 
I can't see much people saying anything in Binance API TG 🤔

**Comment by adampointer** [comment]
https://dev.binance.vision/t/event-user-data-stream-expired-occurs-frequently/466

**Comment by adshao** [comment]
> Hi,
> 
> The user data stream on the futures api disconnects a lot. It is inconsistent. Sometimes it is every 5-10 minutes other times it can be stable for hours. It could well be an issue with Binance or my software. My bot works perfectly on the spot api which is weird.
> 
> Do you experience this too or is it just me?

Sorry, I don't have a bot running for a long time. Seems it is an issue to Binance server.

**Comment by adampointer** [comment]
I will close this.
