### ISSUE TITLE
Return all api errors as APIError

### ISSUE THREAD

**Issue by elboletaire** [adshao/go-binance#156]
Right now, errors arisen by methods like `CreateOrderService.Do()` are returned as golang basic `error` types, concatenating both the error code and the error message in most cases.

I think `APIError` type should be returned always from any of the methods which intervene with the API. 

The current behavior makes it tedious to properly determine which of the API errors has been returned.

The complete list of error codes can be found in the official docs https://binance-docs.github.io/apidocs/spot/en/#error-codes-2

**Comment by adshao** [comment]
Hi @elboletaire , APIError stands for an error received from binance server, there is other errors, for example, [json unmarshal error](https://github.com/adshao/go-binance/blob/master/account_service.go#L26), when calling `Do()` method. I suggest that you should try to convert `err` to `APIError` like `apiError, ok := err.(APIError)`, any other suggestion?

**Comment by elboletaire** [comment]
I may had understood it wrong.

When I do make a limit order to the exchange using [`CreateOrderService.Do()`](https://github.com/adshao/go-binance/blob/cec0e015eb81b8cfd95baa2d70ecc446a755f889/order_service.go#L134), the error returned by that function (if any) is a normal golang `error`, joining both the `code` and the error `message` in a single string. Am I right?

**Comment by afenrir** [comment]
```golang
import "github.com/adshao/go-binance/common"

response, err := CreateOrderService.Do(ctx)
apiError, ok := err.(*common.APIError)
if ok {
    // apiError.Code and apiError.Message can be accessed
}
// do something with response
```

**Comment by adshao** [comment]
@elboletaire Yes, you are right, but if you want to access this error as an `APIError`, you should convert it first as the code example provided by @afenrir , after that, you can check apiError.Code for different errors in [binance doc](https://binance-docs.github.io/apidocs/spot/en/#error-codes-2).
Thanks @afenrir for the example.

**Comment by elboletaire** [comment]
Ah ok! Didn't know about that and will give it a try. Thanks both @afenrir and @adshao :smiley:
