### ISSUE TITLE
Version 2 API

### ISSUE THREAD

**Issue by afenrir** [adshao/go-binance#160]
I need access to a v2 endpoint that the library does not currently offer. This is perhaps a silly question, but if I change the method in the `v2` directory (i.e. a breaking change) will that be accepted as a PR? I'm not 100% sure what that directory is for. 

Edit: The v2 endpoint that I need is the futures account balance: https://binance-docs.github.io/apidocs/futures/en/#futures-account-balance-v2-user_data

I can probably maintain backwards compatibility by retaining the name `WithdrawAvailable` for the JSON field `maxWithdrawAmount`. If I do that, I only need to add new fields. Should I make my changes to the main futures package?

**Comment by addodelgrossi** [comment]
I had the same question about using v2

**Comment by adshao** [comment]
Hi @afenrir @addodelgrossi , sorry for the confusion about the v2 directory, it was introduced in #139 , v2 stands for the version of this package instead of binance API. If it is a breaking change, it's better to use v3,  but I think it's OK to add your change to v2 directory. please keep the main package backwards compatible, that means any new features should be add to v2 directory.

**Comment by adshao** [comment]
For more info about v2 modules, please refer to https://blog.golang.org/v2-go-modules

**Comment by afenrir** [comment]
Thanks for the clarification, @adshao. I am new to go and had not yet come across this aspect of module management. Your link was useful.

As mentioned, I think i can maintain backwards compatibility with the v1 module by retaining the name `WithdrawAvailable` instead of using `maxWithdrawAmount`, which is used by the new API endpoint. 

Would you accept a PR directly to the version 1 package? The only problem I see is that it puts the field name slightly out of sync with that of the API.

Just for clarity, here is the type returned by the v2 API endpoint.
```javascript
{
    "accountAlias": "SgsR",   
    "asset": "USDT",    
    "balance": "122607.35137903", 
    "crossWalletBalance": "23.72469206", 
    "crossUnPnl": "0.00000000",  
    "availableBalance": "23.72469206",       
    "maxWithdrawAmount": "23.72469206"  // maximum amount for transfer out - this field would not be renamed
}
```

And here is the relevant struct in the current codebase:
https://github.com/adshao/go-binance/blob/097cf4adefa9c31be4a0bab2d613fa8f423ba932/futures/account_service.go#L33-L38

**Comment by adshao** [comment]
Hi @afenrir , I suggest only adding this change to v2 directory. Because there will be other new APIs need to be updated in the future, it's better to keep field name synchronized with JSON response.

**Comment by afenrir** [comment]
Sounds good to me.
