### ISSUE TITLE
Configurable websocket endpoint

### ISSUE THREAD

**Issue by elboletaire** [adshao/go-binance#169]
I'd like to use binance's [SPOT testnet](https://testnet.binance.vision/) (I'm tired of "wasting money" for my tests), but I don't see a way to configure the websocket endpoint right now.

Could it be possible to add to the websocket some kind of way to configure the endpoint like there's with the REST client? I see there's a `WSConfig` struct, but its creation is forced in the websocket methods, not allowing to change its value.

**Comment by afenrir** [comment]
It is possible to change the API endpoint for the client like so:

```golang
c := binance.NewClient(key, secret)
c.BaseURL = "https://testnet.binance.vision"
```

**Comment by adshao** [comment]
Hi @elboletaire , thanks for the suggestion, we need a websocket client to set this endpoint just like the REST client. I'll add this feature.

**Comment by elboletaire** [comment]
Now that there are new api clusters deployed (and with the multiple connection problems these days due to the shutdowns in USA), I think it's a great moment to pump this up :)

You can find the new clusters in the following urls:

https://api1.binance.com/api/v3/ping
https://api2.binance.com/api/v3/ping
https://api3.binance.com/api/v3/ping

**Comment by xyq-c-cpp** [comment]
completed, close this.
