### ISSUE TITLE
Adapt to 2020-12-08 changes

### ISSUE THREAD

**Issue by Denton-L** [adshao/go-binance#179]
https://binance-docs.github.io/apidocs/futures/en/#change-log

The first change,

> New field e for event type in payload of streams <symbol>@bookTicker and !bookTicker

breaks unmarshalling. It ends up always returning this error:
```
json: cannot unmarshal string into Go struct field WsBookTickerEvent.E of type int64
```

This happens because Go attempts to first do case-insensitive unmarshalling. Since `e string` and `E int64` are incompatible, when `e` initially tries to unmarshal into `E`, the error is returned. The actual result is fine but since an error is returned, we go into `errHandler()` and `handler()` is not called.

**Comment by afenrir** [comment]
Thanks, @Denton-L.
