### ISSUE TITLE
Update the library to match futures changes made on 2020-12-08

### ISSUE THREAD

**Issue by Denton-L** [adshao/go-binance#182]
https://binance-docs.github.io/apidocs/futures/en/#change-log

# WEBSCOKET

* [x] New field e for event type in payload of streams <symbol>@bookTicker and !bookTicker (#179, #180)
* [ ] New field P for estimated settle price in payload of streams <symbol>@markPrice, <symbol>@markPrice@1s, !markPrice@arr, and !markPrice@arr@1s.
* [ ] New stream <pair>_<contractType>@continuousKline_<interval> for continues contract kline

# REST API

* [ ] New field "estimatedSettlePrice" in response to GET /fapi/v1/premiumIndex
* [x] New fields in response to GET /fapi/v1/exchangeInfo:
  * "pair"
  * "contractType"
  * "deliveryDate"
  * "onboardDate"

* [ ] New endpoint GET /fapi/v1/continuousKlines to get continues contract kline data

# ENUM

* [x] Contract types: PERPETUAL

**Comment by adshao** [comment]
thanks @Denton-L for the TODO list.

**Comment by afenrir** [comment]
The following were completed in #184 

- New fields in response to GET /fapi/v1/exchangeInfo
- Contract types: PERPETUAL

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
