### ISSUE TITLE
Error trying to use "v2" module

### ISSUE THREAD

**Issue by tschaboo** [adshao/go-binance#189]
When trying this code
```
package main

import (
	_ "github.com/adshao/go-binance/v2"
)

func main() {
}
```
I get
```
go: finding module for package github.com/adshao/go-binance/v2
main.go:4:2: module github.com/adshao/go-binance@latest found (v0.0.0-20201221124815-35bd9c8231f3), but does not contain package github.com/adshao/go-binance/v2

Compilation finished with exit code 1
```

I was unable to solve this issue myself. Am very new to golang. Using go 1.15.6.

**Comment by afenrir** [comment]
You can install it with.

```
go get -u github.com/adshao/go-binance/v2@35bd9c8
```

Once v1 has been removed from the master branch (#183) you should be able to just install it normally.

**Comment by tschaboo** [comment]
Thank you very much for your help, that worked!

(I leave the ticket open so that others can find it easier)

**Comment by adshao** [comment]
hi @tschaboo , please use ```go get -u github.com/adshao/go-binance/v2@v2.2.0``` since v1 has been remove from master branch.
