### ISSUE TITLE
Toggling on and off a Websocket stream

### ISSUE THREAD

**Issue by t00ts** [adshao/go-binance#19]
What would be the correct / elegant way to stop the `WsKlineServe` client (or any other of the websocket clients)?

I see it's easy to get it up and running, but I'm not sure on how I can turn it on and off programatically.

Thanks!

**Comment by adshao** [comment]
@t00ts good question, I think we need a stopC chan to notify the program to exit. I will add the feature this week.

**Comment by adshao** [comment]
Hi @t00ts , it is done by pr #23 , please follow the example: https://github.com/adshao/go-binance/#depth
pls let me know if there is any problem.
