### ISSUE TITLE
Doesn't work with go dep tool

### ISSUE THREAD

**Issue by nu11ptr** [adshao/go-binance#2]
Given this is going to be the new de facto standard golang dependency tool thought you might be interested to know it doesn't work.

```
scott@saruman:~/go/src/gitlab.com/apisw/myproject$ dep ensure -add github.com/adshao/go-binance
Fetching sources...

ensure Solve(): No versions of github.com/adshao/go-binance met constraints:
	master: unexpected error while defensively updating submodules: : command failed: [git submodule update --init --recursive]: exit status 128
```

The issue seems to be some issue with a git submodule in the vendor directory - one time while doing "go get" I also got the error which is slightly more verbose giving some insight:

```
scott@saruman:~/go/src/gitlab.com/apisw/myproject$ go get github.com/adshao/go-binance
# cd /home/scott/go/src/github.com/adshao/go-binance; git submodule update --init --recursive
fatal: no submodule mapping found in .gitmodules for path 'vendor/github.com/bitly/go-simplejson'
package github.com/adshao/go-binance: exit status 128
```

Strangely, simply issuing the "go get" again and it worked. However, "dep ensure" never works. Thoughts?

**Comment by adshao** [comment]
@nu11ptr thanks for the feedback. 
I have tested the dep tool and it works for me. could you add master branch to dep command as following:
`dep ensure -add github.com/adshao/go-binance@master`
And it would be better if you can provide Gopkg.toml when that failed.

**Comment by rskumar** [comment]
If its related, on Windows installing it throws error - 

```bash
> go get -u github.com/adshao/go-binance
# cd C:\go_projects\src\github.com\adshao\go-binance; git submodule update --init --recursive
fatal: No url found for submodule path 'vendor/github.com/bitly/go-simplejson' in .gitmodules
package github.com/adshao/go-binance: exit status 128
```

**Comment by nu11ptr** [comment]
This is the same exit code (128) and the same module (go-simplejson) mentioned, but my issued appeared on linux. After your first message I was going to go back and try to add it to a blank project, but haven't had a chance yet. It might be conflicting with my YAML module, not sure.

**Comment by adshao** [comment]
It seems there is mistake of your .gitmodules setting, could you please refer to following links to deal with it:
https://github.com/openshift/origin/issues/12139#issuecomment-264955741
https://stackoverflow.com/questions/4185365/no-submodule-mapping-found-in-gitmodule-for-a-path-thats-not-a-submodule

**Comment by svanas** [comment]
I have this problem with `go get` on Darwin/macOS. I suggest we remove the vendored modules altogether.

**Comment by adshao** [comment]
Hi @nu11ptr @rskumar @svanas , sorry for that, it was caused by the mistake about vendor init, I have fixed it. please issue `git pull master` at your convenience.
