### ISSUE TITLE
Add support for Binance.US

### ISSUE THREAD

**Issue by cconover** [adshao/go-binance#216]
Since [US users cannot use binance.com anymore](https://in.finance.yahoo.com/news/binance-finally-blocks-united-states-115803718.html) and instead must use [https://www.binance.us](https://www.binance.us), can you add support for their API URL as well?

**Comment by adshao** [comment]
> Since [US users cannot use binance.com anymore](https://in.finance.yahoo.com/news/binance-finally-blocks-united-states-115803718.html) and instead must use https://www.binance.us, can you add support for their API URL as well?

Could you try to set base url? ```client.BaseURL = "https://www.binance.us"```

**Comment by cconover** [comment]
Looks like that works, thanks! I must've missed that in the docs 🙃
