### ISSUE TITLE
Generate new release

### ISSUE THREAD

**Issue by Drathveloper** [adshao/go-binance#217]
Hello, 

Could you generate a new tag with a new version? I'm interested in the testnet stuff you added recently.

Thanks in advance

**Comment by rodsher** [comment]
Hello! I'm also interested in the testnet feature. Can I help with a new release?

**Comment by adshao** [comment]
> Hello,
> 
> Could you generate a new tag with a new version? I'm interested in the testnet stuff you added recently.
> 
> Thanks in advance

Done, just add a new tag v2.2.1. Let me know if there is any problem.

**Comment by adshao** [comment]
> Hello! I'm also interested in the testnet feature. Can I help with a new release?

Please use v2.2.1. Let me know if there is any problem.

**Comment by rodsher** [comment]
@adshao You can close issue. Version released.
