### ISSUE TITLE
Testnet Stream Websocket Endpoints not receiving events.

### ISSUE THREAD

**Issue by phea** [adshao/go-binance#219]
When setting `binance.UseTestnet = true` the public streams do not receive any events.

```go
package main

import (
	"log"
	"os"
	"os/signal"

	binance "github.com/adshao/go-binance/v2"
)

func main() {
	binance.UseTestnet = true
	interrupt := make(chan os.Signal, 1)
	signal.Notify(interrupt, os.Interrupt)

	wsTradeHandler := func(event *binance.WsAggTradeEvent) {
		log.Println(event)
	}

	errHandler := func(err error) {
		log.Println(err)
	}
	_, _, err := binance.WsAggTradeServe("BNBUSDT", wsTradeHandler, errHandler)
	if err != nil {
		log.Fatal(err)
	}
	<-interrupt
}
```

**Comment by rodsher** [comment]
Hi! I have tested the method `binance.WsTradeServe` with the symbol `BTCUSDT`. Events come but rarely. Please, try to launch the program and wait 15-30 minutes.

**Comment by elboletaire** [comment]
You can also produce your own events trading on your own.. is how I did test it by myself last time in the testnet, otherwise it's completely flat.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
