### ISSUE TITLE
Price is zero in order response and can't get order because it doesn't exists

### ISSUE THREAD

**Issue by Gilgames000** [adshao/go-binance#223]
Hi! If I do this
```
order, err := client.NewCreateOrderService().
		Symbol(baseAsset + quotedAsset).
		Side(binance.SideTypeBuy).
		Type(binance.OrderTypeMarket).
		QuoteOrderQty(fmt.Sprintf("%.8f", quotedAssetQty)).
		Do(context.Background())
```
the order gets filled, but `order.Price` is always `0.00000000` (all the other fields look good). So I thought, well I could just fetch the order and check the price from there:
```
order, err := client.NewGetOrderService().
		Symbol(symbol).
		OrderID(id).
		Do(context.Background())
```
and I get back `<APIError> code=-2013, msg=Order does not exist.`. I also tried with `OrigClientOrderID` instead of `OrderID`, same result. What am I doing wrong?

**Comment by vladimirfilin** [comment]
Hi!
> ....but order.Price is always 0.00000000

This is normal for market orders .OrderTypeMarket
This is not explicitly stated in the documentation, but is mentioned in the examples to [New Order (TRADE) POST /api/v3/order](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade)
You can get full information from order transactions from [Account Trade List (USER_DATA) GET /api/v3/myTrades](https://binance-docs.github.io/apidocs/spot/en/#account-trade-list-user_data)

> and I get back <APIError> code=-2013, msg=Order does not exist.

Yes. I also get this error if request data immediately after placing order. Delay is about 20 seconds last two months.

**Comment by Gilgames000** [comment]
Oh, I see, thanks! So is there any way to get the price from the order response you get from the GetOrderService execution without having to make another request? I mean, I could just iterate through the fills and calculate the average buy price, but do I have the guarantee that the order response for a _buy market order_ contains all of the fills when I get it (i.e. the order is completely filled, not partially)?

**Comment by vladimirfilin** [comment]
> ...order response for a buy market order contains all of the fills...

Exact answer can only be given by BINANCE developers. I'm not one of them. My understanding: if at [New Order (TRADE) POST /api/v3/order](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade) at Response FULL the "status": "FILLED", then "fills": [...] must contain all order transactions.

> ...calculate the average buy price...

Just in case. The transaction [fee can be charged in BNB](https://www.binance.com/en/support/articles/360043011652), i.e. in a currency other than the trading pair. Will a simple AVG work for you in this case?

**Comment by Gilgames000** [comment]
> My understanding: if at New Order (TRADE) POST /api/v3/order at Response FULL the "status": "FILLED", then "fills": [...] must contain all order transactions.

Oh, my question wasn't actually about whether or not an order response with status FILLED would return all the fills, but rather if the order response of a buy market order is guaranteed to return with the status FILLED (i.e. if it either gets filled before returning or it fails).  


> Just in case. The transaction fee can be charged in BNB, i.e. in a currency other than the trading pair. Will a simple AVG work for you in this case?

As of now, I'm using BNB for fees because this way I can just get my coin balance and sell all of it without having to take into account fees (unless I'm trading BNB/BTC),
