### ISSUE TITLE
Position Information V2

### ISSUE THREAD

**Issue by Timouri** [adshao/go-binance#224]
How can i perform this request?
https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data

**Comment by adshao** [comment]
> How can i perform this request?
> https://binance-docs.github.io/apidocs/futures/en/#position-information-v2-user_data

Hi @Timouri , please use `client. NewGetPositionRiskService().Do(ctx)`

**Comment by CodyGuo** [comment]
https://github.com/adshao/go-binance/blob/master/v2/futures/position_risk.go#L17
```shell
GET /fapi/v2/positionRisk (HMAC SHA256)
```
当前不支持v2版本接口，能否支持一下？
