### ISSUE TITLE
Websocket data stream stuck to

### ISSUE THREAD

**Issue by moartinz** [adshao/go-binance#226]
Hi guys, 
I am using the websocket connection for screening current price on BTC markets/pairs. 
I am noticing that after the program starts the data stream works fine for a little bit but after a little while the price streams gets stuck to a value, not changing over time. In Binance orderbook (opened in a side window) it changes quite rapidly. 

Anyone faced this issue already? Any hint on what can this be due to?

**Comment by phea** [comment]
What is a little while? According to the Binance API documents, they will close the websocket connection after 24 hours.

You can try setting the package level flag WebsocketKeepalive to true.

```go

var (
	// WebsocketTimeout is an interval for sending ping/pong messages if WebsocketKeepalive is enabled
	WebsocketTimeout = time.Second * 60
	// WebsocketKeepalive enables sending ping/pong messages to check the connection stability
	WebsocketKeepalive = false
)
```

https://pkg.go.dev/github.com/adshao/go-binance?utm_source=godoc#pkg-variables

**Comment by phea** [comment]
Update. I too experienced disconnects even though I have set the keepalive flag to be true. I reread Binance's API and I guess they mean that they will disconnect you after 24 hours, no matter what. This means you have to monitor the returned `doneC` channel for disconnects.

My solution was just to fire a goroutine to monitor each doneC.
```go
monitorWS := func(sym string, ch chan struct{}) {
  go func() {
    <-ch
    // ws disconnected, try to re-established.
    doneC, _, err := binance.WsAggTradeServe(sym, tradeHandler, errHandler)
    if err != nil {
      log.Printf("error registering symbol %s: %v", sym, err)
      return
    }

    monitorWS(sym, doneC)
  }()
}

wg := sync.WaitGroup{}
for _, b := range books {
    wg.Add(1)
    go func(b OrderBook) {
      defer wg.Done()

      doneC, _, err := binance.WsAggTradeServe(b.Symbol, tradeHandler, errHandler)
      if err != nil {
        log.Printf("error registering symbol %s: %v", b.Symbol, err)
      }

      monitorWS(b.Symbol, doneC)
    }(b)
}
wg.Wait()
```

**Comment by jon4hz** [comment]
Hi, I'm currently facing the same problem but I get a few errors with your code. I'm fairly new to golang and kinda lost. Somehow I get an "undeclared name" error for `monitorWS`, `books` and `OrderBook`. Could you help me out to get this working. Stable and automatically reconnecting websockets are necessary for my project.

**Comment by phea** [comment]
@jon4hz `books` and `OrderBook` are just my own structs that hold OrderBook and symbol information. You will have to customize my code example for your own code. The main takeaway is to launch a goroutine for each doneC channel to monitor when binance drops the websocket connection.

If you haven't already done so, I suggest going through the golang tour at https://tour.golang.org to better understand how go handles concurrency.

**Comment by jon4hz** [comment]
Hey, sorry to bother you again. In the mean time, I improved my go skills a bit (at least I think so).
But something in your code is still bothering me. Did I understand it correctly, that your code only reconnects once? And if the reconnect attempt fails (WsAggTradeServe returns an err), it stops because you have a return when you check for the err in your monitorWS function?

**Comment by jon4hz** [comment]
So I did a little testing and came to the conclusion that @phea only reconnects the websockets once, if the fail because the internet connection cuts for example. 

To reconnect *always* I added a for loop which only ends, if the error is nil.

```
monitorWS := func(sym string, ch chan struct{}) {
  go func() {
    <-ch
    // ws disconnected, try to re-establish.
    doneC, _, err := binance.WsAggTradeServe(sym, tradeHandler, errHandler)
    if err != nil {
      log.Printf("error registering symbol %s: %v", sym, err)
      for err != nil {
		time.Sleep(time.Second / 10)
	    doneC, _, err = binance.WsAggTradeServe(sym, wsDepthHandler, errHandler)
	  }
    }

    monitorWS(sym, doneC)
  }()
}

wg := sync.WaitGroup{}
for _, b := range books {
    wg.Add(1)
    go func(b OrderBook) {
      defer wg.Done()

      doneC, _, err := binance.WsAggTradeServe(b.Symbol, tradeHandler, errHandler)
      if err != nil {
        log.Printf("error registering symbol %s: %v", b.Symbol, err)
		for err != nil {
		  time.Sleep(time.Second / 10)
		  doneC, _, err = binance.WsAggTradeServe(sym, wsDepthHandler, errHandler)
	    }
      }

      monitorWS(b.Symbol, doneC)
    }(b)
}
wg.Wait()
```

**Comment by Milerius** [comment]
Why not simply do:

```go
<-doneC
//! Your code post disconnection
```

?

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
