### ISSUE TITLE
If we need to handle the ping in go-binance?

### ISSUE THREAD

**Issue by zhouziyan** [adshao/go-binance#234]
According to binance's doc:

> The websocket server will send a ping frame every 5 minutes. If the websocket server does not receive a pong frame back from the connection within a 15 minute period, the connection will be disconnected. Unsolicited pong frames are allowed.

**Comment by grishinsana** [comment]
gorilla websocket package sets ping handler by default

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
