### ISSUE TITLE
How to use one websocket connection for several coins?

### ISSUE THREAD

**Issue by jokaorgua** [adshao/go-binance#248]
Hello.

Due to the code to get real time prices I should use WsKlineServe function. This function creates new connection for every coin and interval. So if I have to monitor 150 coins on 5 intervals the lib will create 750 connections? Seems to me binance will ban for that :( 

Is there any way to use https://github.com/binance/binance-spot-api-docs/blob/master/web-socket-streams.md#live-subscribingunsubscribing-to-streams feature to reduce number of connections?

**Comment by jokaorgua** [comment]
found a solution here https://github.com/adshao/go-binance/pull/243

**Comment by felipeneuwald** [comment]
You can use, e.g., `go get github.com/adshao/go-binance/v2@1e8028b94cc07e2e608ec01c11694610d953f851` until it is not released.
