### ISSUE TITLE
how to / can't use Do(ctx context.Context, opts ...RequestOption)

### ISSUE THREAD

**Issue by klouskingsley** [adshao/go-binance#261]
I want set some extra params for the request, because the `RequestOption` type is

```go
type RequestOption func(*request)
```

so my code is 

```go
res, err := client.NewMarginLoanService().
		Asset("BTC").
		Amount("0.001").
		Do(context.Background(), func(request *interface{}) {

	})
```

but I got the error

```
Cannot use 'func(request *interface{}) { }' (type func(request *interface{})) as type RequestOption
```

how do I write the right way to use RequestOption?

**Comment by Dashift** [comment]
This is one of the go design style called "functional-options"

It usually write like this:
```
c.Do(context.TODO(),WithSomeOpt1(arg1),WithSomeOpt2(arg2))
```

The func `WithSomeOpt1()` and `WithSomeOpt2()` will in same package as the client you are using

more informations:  https://github.com/uber-go/guide/blob/master/style.md#functional-options

**Comment by klouskingsley** [comment]
Thanks @Dashift , learn a lot from u ~
