### ISSUE TITLE
Found a bug in ExchangeInfoService

### ISSUE THREAD

**Issue by CharonShen** [adshao/go-binance#267]
When I use Symbols(), I get the following error:
“<APIError> code=-1100, msg=Illegal characters found in parameter 'symbols'; legal range is '^\[("[A-Z0-9-_.]{1,20}"(,"[A-Z0-9-_.]{1,20}"){0,}){0,1}\]$'.”

**Comment by icamys** [comment]
@CharonShen Just encountered the same issue. Did you found any ideomatic solution?
