### ISSUE TITLE
On August 01, 2021 02:00 AM UTC the WAPI endpoints will be discontinued

### ISSUE THREAD

**Issue by lxt1045** [adshao/go-binance#273]
https://binance-docs.github.io/apidocs/spot/en/#change-log

The WAPI endpoints have been removed from Binance API Documentation.To ensure your trading strategies are not affected, all API users are encouraged to upgrade trading bots to SAPI endpoints as soon as possible.

**Comment by pooyakn** [comment]
any update on this?

**Comment by RoanBrand** [comment]
Just searched explicitly for this, need SAPI implementation asap.
I can try implement and make PR for it if it will be considered?

**Comment by pooyakn** [comment]
> Just searched explicitly for this, I need SAPI implementation asap for withdrawals.
> The Binance API changelog specifically mentions just the following wapi will be discontinued:
> 
> ```
> GET /wapi/v3/systemStatus.html
> POST /wapi/v3/withdraw.html
> GET /wapi/v3/depositHistory.html
> GET /wapi/v3/withdrawHistory.html
> GET /wapi/v3/depositAddress.html
> GET /wapi/v3/accountStatus.html
> GET /wapi/v3/apiTradingStatus.html
> GET /wapi/v3/userAssetDribbletLog.html
> GET /wapi/v3/assetDetail.html
> GET /wapi/v3/tradeFee.html
> GET /wapi/v3/sub-account/list.html
> GET /wapi/v3/sub-account/transfer/history.html
> POST /wapi/v3/sub-account/transfer.html
> GET /wapi/v3/sub-account/assets.html
> ```
> 
> I can try implement and make PR for it if it will be considered?

A pull req was created 3 month ago and it's not merged yet.
https://github.com/adshao/go-binance/pull/247

**Comment by adshao** [comment]
> Just searched explicitly for this, I need SAPI implementation asap for withdrawals.
> The Binance API changelog specifically mentions just the following wapi will be discontinued:
> 
> ```
> GET /wapi/v3/systemStatus.html
> POST /wapi/v3/withdraw.html
> GET /wapi/v3/depositHistory.html
> GET /wapi/v3/withdrawHistory.html
> GET /wapi/v3/depositAddress.html
> GET /wapi/v3/accountStatus.html
> GET /wapi/v3/apiTradingStatus.html
> GET /wapi/v3/userAssetDribbletLog.html
> GET /wapi/v3/assetDetail.html
> GET /wapi/v3/tradeFee.html
> GET /wapi/v3/sub-account/list.html
> GET /wapi/v3/sub-account/transfer/history.html
> POST /wapi/v3/sub-account/transfer.html
> GET /wapi/v3/sub-account/assets.html
> ```
> 
> I can try implement and make PR for it if it will be considered?

Yes, really appreciate if you can create a PR for it.

**Comment by adshao** [comment]
> > Just searched explicitly for this, I need SAPI implementation asap for withdrawals.
> > The Binance API changelog specifically mentions just the following wapi will be discontinued:
> > ```
> > GET /wapi/v3/systemStatus.html
> > POST /wapi/v3/withdraw.html
> > GET /wapi/v3/depositHistory.html
> > GET /wapi/v3/withdrawHistory.html
> > GET /wapi/v3/depositAddress.html
> > GET /wapi/v3/accountStatus.html
> > GET /wapi/v3/apiTradingStatus.html
> > GET /wapi/v3/userAssetDribbletLog.html
> > GET /wapi/v3/assetDetail.html
> > GET /wapi/v3/tradeFee.html
> > GET /wapi/v3/sub-account/list.html
> > GET /wapi/v3/sub-account/transfer/history.html
> > POST /wapi/v3/sub-account/transfer.html
> > GET /wapi/v3/sub-account/assets.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can try implement and make PR for it if it will be considered?
> 
> A pull req was created 3 month ago and it's not merged yet.
> #247

This PR is out of date and does not pass the Travis CI check.

**Comment by adshao** [comment]
I have changed wapi to sapi in #282 , please use v2.3.0.
