### ISSUE TITLE
WsCombinedKlineServe websocket

### ISSUE THREAD

**Issue by Qasemt** [adshao/go-binance#275]
hi :)  
**WsCombinedKlineServe** does not work for multiple symbol
tanx 
![image](https://user-images.githubusercontent.com/2597895/122748162-222eeb80-d2a1-11eb-81e1-85671c49fb61.png)

**Comment by Qasemt** [comment]
only first symbol (btc) arrive from webservice

**Comment by marvin-hansen** [comment]
Start multiple socket streams for multiple symbols as shown in below.  
Note, if you want to stop data streams per symbol, 
 then you have to track each close channel individually and implement a stop stream method. 


![image](https://user-images.githubusercontent.com/24190940/131474115-26fa820a-9fc4-4674-a97d-15b3a43e7ed5.png)

**Comment by boskiv** [comment]
Working well as today
```
package main

import (
	"fmt"
	"github.com/adshao/go-binance/v2"
)

func main() {

	pairs := map[string]string{
		"BTCUSDT": "1m",
		"ETHUSDT": "1m",
	}

	wsKlineHandler := func(event *binance.WsKlineEvent) {
		fmt.Println(event)
	}
	errHandler := func(err error) {
		fmt.Println(err)
	}
	doneC, _, err := binance.WsCombinedKlineServe(pairs, wsKlineHandler, errHandler)
	if err != nil {
		fmt.Println(err)
		return
	}
	<-doneC
}
```

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
