### ISSUE TITLE
trade_service missing from delivery APIs

### ISSUE THREAD

**Issue by shanewright** [adshao/go-binance#280]
Hi

Support for recent/historic/aggregated trades is present for the futures package, but not for the delivery (COIN-M) package, the Binance APIs are almost identical..
https://binance-docs.github.io/apidocs/futures/en/#recent-trades-list
https://binance-docs.github.io/apidocs/delivery/en/#recent-trades-list

The relevant code/API is present here for futures:
https://github.com/adshao/go-binance/blob/master/v2/futures/trade_service.go

...but not in the delivery package.

Is this an accidental omission or there is a technical reason?  I can put together a patch/PR if that would be helpful?

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
