### ISSUE TITLE
this package doesn't work in wasm

### ISSUE THREAD

**Issue by Milerius** [adshao/go-binance#284]
<img width="543" alt="Capture d’écran 2021-07-17 à 10 04 50" src="https://user-images.githubusercontent.com/21139416/126030647-dc906297-75d2-4d27-a606-e8ba3eb0094c.png">

I think websocket in the browser should work - why it is not the case ? (gorilla doesn't support wasm)
https://github.com/gorilla/websocket/issues/432

https://github.com/nhooyr/websocket it's seems supported on this package, would be worth to drop gorilla websocket tbh

For me it's a bit critical, being able to build for wasm should be a priority nowadays in crypto, most of the project are moving towards this direction especially for decentralized node in the browser

cc @adshao

**Comment by adshao** [comment]
> <img alt="Capture d’écran 2021-07-17 à 10 04 50" width="543" src="https://user-images.githubusercontent.com/21139416/126030647-dc906297-75d2-4d27-a606-e8ba3eb0094c.png">
> 
> I think websocket in the browser should work - why it is not the case ? (gorilla doesn't support wasm)
> [gorilla/websocket#432](https://github.com/gorilla/websocket/issues/432)
> 
> https://github.com/nhooyr/websocket it's seems supported on this package, would be worth to drop gorilla websocket tbh
> 
> For me it's a bit critical, being able to build for wasm should be a priority nowadays in crypto, most of the project are moving towards this direction especially for decentralized node in the browser
> 
> cc @adshao

Hi @Milerius , I think it's ok to use https://github.com/nhooyr/websocket instead of gorilla websocket, do you want to submit a PR for it? or I'll try to implement it in next month.

**Comment by Milerius** [comment]
> > <img alt="Capture d’écran 2021-07-17 à 10 04 50" width="543" src="https://user-images.githubusercontent.com/21139416/126030647-dc906297-75d2-4d27-a606-e8ba3eb0094c.png">
> > I think websocket in the browser should work - why it is not the case ? (gorilla doesn't support wasm)
> > [gorilla/websocket#432](https://github.com/gorilla/websocket/issues/432)
> > https://github.com/nhooyr/websocket it's seems supported on this package, would be worth to drop gorilla websocket tbh
> > For me it's a bit critical, being able to build for wasm should be a priority nowadays in crypto, most of the project are moving towards this direction especially for decentralized node in the browser
> > cc @adshao
> 
> Hi @Milerius , I think it's ok to use https://github.com/nhooyr/websocket instead of gorilla websocket, do you want to submit a PR for it? or I'll try to implement it in next month.

I have a working implementation on my machine i can submit a patch this week

**Comment by Milerius** [comment]
Thanks for the merge @adshao
