### ISSUE TITLE
GetExchangeInfo service is not implemented

### ISSUE THREAD

**Issue by rakanalh** [adshao/go-binance#3]
Hello,

I was trying to use your client for writing a price ticker for Binance... i noticed that i can't list exchanges and therefore, i cannot fetch the symbols available to get tickers for.
the API: https://github.com/binance-exchange/binance-official-api-docs/blob/master/rest-api.md#exchange-information is an official one by Binance so i was wondering why it's not available in your wrapper?

Update: Since i would like to get price data using websockets eventually, i have to fetch tickers through the API provided:
```
prices, err := client.NewListPricesService().Do(context.Background())
if err != nil {
    fmt.Println(err)
    return
}
for _, p := range prices {
    fmt.Println(p)
}
```
and then get the symbol from this as a workaround.

Thanks,
Rakan

**Comment by svanas** [comment]
I opened this PR: https://github.com/adshao/go-binance/pull/7. @adshao please review. Thanks!

**Comment by adshao** [comment]
thanks @svanas , comment updated https://github.com/adshao/go-binance/pull/7#issuecomment-358637512

**Comment by adshao** [comment]
close this issue as pr #7 merged
