### ISSUE TITLE
请问有没有计划开发整合SDK？

### ISSUE THREAD

**Issue by nashjob** [adshao/go-binance#30]
请问有没有计划开发包含主流交易所的整合性SDK，看了github上的项目，貌似只有一个，支持的还不是很完善。

**Comment by adshao** [comment]
暂时还没有这个计划，不知具体需求是？
你是指这个项目么？https://github.com/nntaoli-project/GoEx
基于这个项目改进应该比重新写的工作量要小。

**Comment by nashjob** [comment]
恩，类似于这个项目，您这个项目做得很赞，非常感谢，已经引入工程。没有其他问题了。可以关闭了。再次感谢
