### ISSUE TITLE
Missing API Key Permission USER_DATA API

### ISSUE THREAD

**Issue by frostrock7** [adshao/go-binance#304]
Missing GET` /sapi/v1/account/apiRestrictions (HMAC SHA256)

Very usefull for checking before trading for example.

**Comment by kunsonx** [comment]
@Antohny-frost https://github.com/crypto-zero/go-binance

**Comment by halink0803** [comment]
@frostrock7 I think it is easy to create a PR to add this api.

**Comment by csquan** [comment]
does not work

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
