### ISSUE TITLE
Why ? msg=Signature for this request is not valid

### ISSUE THREAD

**Issue by Go36625090** [adshao/go-binance#310]
<nil> <APIError> code=-1022, msg=Signature for this request is not valid.
<APIError> code=-1022, msg=Signature for this request is not valid.

code: 
`
import (
	"context"
	"github.com/adshao/go-binance/v2/delivery"
	"github.com/adshao/go-binance/v2/futures"
	"github.com/hashicorp/go-hclog"
)

client := delivery.NewClient(cfg.Account.Key, cfg.Account.Secret)

client.NewSetServerTimeService().Do(context.Background())

orders, err := client.NewGetOrderService().Do(context.Background())
	if err != nil {
		logger.Error("list orders failed", "err", err)
		return
	}
	logger.Info("orders", "list", orders)
`

**Comment by abrekhov** [comment]
Same issue.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
