### ISSUE TITLE
There are some problems between nhooyr/websocket package and Binance WebSocket API.

### ISSUE THREAD

**Issue by XanderShum** [adshao/go-binance#321]
I ran into the same problem as follows: 
https://github.com/nhooyr/websocket/issues/315

I think this is a problem we need to pay attention to. Obviously there are some problems with nhooyr/websocket.

**Comment by XanderShum** [comment]
@adshao

**Comment by adshao** [comment]
> I ran into the same problem as follows: [nhooyr/websocket#315](https://github.com/nhooyr/websocket/issues/315)
> 
> I think this is a problem we need to pay attention to. Obviously there are some problems with nhooyr/websocket.

Thanks @XanderShum , I'll try to reproduce it.

**Comment by adshao** [comment]
@XanderShum  Hard to reproduce, is there any suggestion for this issue? I found https://github.com/nhooyr/websocket is not actively maintained now, should we change to use the dev branch of nhooyr/websocket, or revert the pr #290 ?

**Comment by ArminEbrahimi** [comment]
@adshao @XanderShum Would you please revert the pr #290 ?

**Comment by XanderShum** [comment]
> @XanderShum Hard to reproduce, is there any suggestion for this issue? I found https://github.com/nhooyr/websocket is not actively maintained now, should we change to use the dev branch of nhooyr/websocket, or revert the pr #290 ?

**Comment by XanderShum** [comment]
@adshao My current solution is to use the dev branch of nhooyr/websocket, but it's not perfect.

**Comment by ArminEbrahimi** [comment]
> @adshao @XanderShum Would you please revert the pr #290 ?

Any Updaye? @adshao #BlockingIssue

**Comment by adshao** [comment]
> > @adshao @XanderShum Would you please revert the pr #290 ?
> 
> Any Updaye? @adshao #BlockingIssue

I'll change  nhooyr/websocket to dev branch

**Comment by adshao** [comment]
> > @adshao @XanderShum Would you please revert the pr #290 ?
> 
> Any Updaye? @adshao #BlockingIssue

I'm reverting #290 in #357

**Comment by adshao** [comment]
@ArminEbrahimi @XanderShum nhooyr.io/websocket is reverted to github.com/gorilla/websocket, let me know if there is any problems, thanks.
