### ISSUE TITLE
Please bump the tag to 2.3.3

### ISSUE THREAD

**Issue by sugardose** [adshao/go-binance#322]
There are recent updates that got merged and are not making it to golang proxy repositories because the tag did not get updated.

Example: https://github.com/adshao/go-binance/commit/7ef52655a5e54e1cde38d3120290712edd0e5e73

**Comment by adshao** [comment]
> There are recent updates that got merged and are not making it to golang proxy repositories because the tag did not get updated.
> 
> Example: [7ef5265](https://github.com/adshao/go-binance/commit/7ef52655a5e54e1cde38d3120290712edd0e5e73)

thanks, I just pushed tag v2.3.3.
