### ISSUE TITLE
call in sequence

### ISSUE THREAD

**Issue by gutofurlan** [adshao/go-binance#339]
good night,

I need to call 3 buy and sell orders in sequence, all market orders.
Is there a way to do this?
I buy one coin, then I buy another, and then I buy another.

How do I guarantee that the order was carried out?

thanks

**Comment by adshao** [comment]
> good night,
> 
> I need to call 3 buy and sell orders in sequence, all market orders. Is there a way to do this? I buy one coin, then I buy another, and then I buy another.
> 
> How do I guarantee that the order was carried out?
> 
> thanks

Do you mean the batch orders? You can use GetOrderService to check order status.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
