### ISSUE TITLE
Lot size conversion

### ISSUE THREAD

**Issue by barthr** [adshao/go-binance#34]
Heya!

I've been using this package for a while now and really like it. There was one problem I encountered when creating orders and that was with the lot sizes. I wrote my own function to convert an amount to a lot sized amount. 

Is this something you are interested in to include in the library?

Greetings

**Comment by adshao** [comment]
hi @barthr , of course, pr is welcome, I really appreciate it.

**Comment by barthr** [comment]
Ok nice! I will add it including some tests

**Comment by barthr** [comment]
solved by #35
