### ISSUE TITLE
ws order vs order consistency

### ISSUE THREAD

**Issue by ljubomirb** [adshao/go-binance#341]
If I could have two suggestion, it would be:
- if naming could be more in tune with binance naming (that is for sure cryptic itself to non trader, but nevertheless, one needs to look at there because it is somewhat better documented)
- and also - if everything can be somewhat more "standardized". Like, for example - "orders"
Here you have two things that come from different places (REST and WS). Nevertheless, they do the same thing, yet they differ in fields that could be the same.
*`binance.WsOrderUpdate `and *`binance.Order `have same fields, but... order side is once `string`, once `binance.SideType`. The same goes for `status`, and such things... There are also fields that have same purpose, but different naming. It is also not helpful if naming is somewhat different from original binance, introducing even more mess into cryptic terminology, and guessing what would be the difference between "_volume_", "_quantity_" and all its variants. :)

(edit: also ClientOrderId vs ClientOrderID)...

**Comment by xyq-c-cpp** [comment]
great, my opinion is same as yours. thanks.
