### ISSUE TITLE
ERROR: -1021, Timestamp for this request is outside of the recvWindow.

### ISSUE THREAD

**Issue by ljubomirb** [adshao/go-binance#344]
Hi,
I received this error, but it is not happening every time, and it probably happens when I give order. I only guess, since error did not show up until today, so it's hard for me to find it. But, as for google tells me, it is probably because computer time and binance time are different as explained [here](https://dev.binance.vision/t/error-timestamp-for-this-request-is-outside-of-the-recvwindow/1357)
The solution binance tells us is that we must sync computer time with binance server, whereas I would like to avoid this.
Thus, I've seen that there is a parameter `recvWindow` that can be changed when giving order, as shown in documentation [here](https://binance-docs.github.io/apidocs/spot/en/#new-order-trade). I also see you have it in code on a few places, so I guess it is all already here, just I don't know how to use it, or something small is missing.
My questions are:
- can I give order with larger `recWindow`
- or can I set entire `client` (globally) to have `recWindow` var bigger, and if so, where?

Thank you for your time!

**Comment by ljubomirb** [comment]
Ok, so I think I've found a way to push `WithRecvWindow` option, hope I'm doing it right.
So, order might now look something like this:
```
order, err := client.NewCreateOrderService().Symbol(symbolpair).
		Side(side).Type(binance.OrderTypeMarket).NewClientOrderID(customID).
		Quantity(quantity)).                  //Price(price))
		Do(context.Background(), binance.WithRecvWindow(10000)) //10 secs, default is 5
return order, err
```

**Comment by adshao** [comment]
> 

Hi @ljubomirb , You are right, `RecvWindow` should be passed in `Do(ctx, options...)`. Currently there is not global recvWindow since not every API needs it.
It is recommended that you should keep your host time synced with binance server.
