### ISSUE TITLE
order quantity precision issue

### ISSUE THREAD

**Issue by Icarus9913** [adshao/go-binance#374]
I new an order with quantity two decimal point, but return me an error:
> &common.APIError{Code:-1111, Message:"Precision is over the maximum defined for this asset."}

For example: my order is : quantity 428.94, future, LONG, BUY, OrderTypeMarket, Symbol:"FILUSTD"

It's very strange. Actually I think the server supports two decimal points for quantity.

**Comment by Icarus9913** [comment]
cc @adshao

**Comment by adshao** [comment]
you should check asset precision in [exchangeInfo API](https://binance-docs.github.io/apidocs/spot/en/#exchange-information)
