### ISSUE TITLE
Unable to set testnet true for Websocket data pulling 

### ISSUE THREAD

**Issue by TanjinAlam** [adshao/go-binance#378]
binance.UseTestnet = true
futures.UseTestnet = true

Helpts to enable testnet true for api data pulling but how to set testnet true for websocket 

	wsHandler := func(event *binance.WsUserDataEvent) {
		fmt.Println(event)
	}
	errHandler := func(err error) {
		fmt.Println(err)
	}
	
	doneC, _, err := binance.WsUserDataServe("jMyAD5lUpokExjQY0y0XVfCUW9HaXHpiAE03jMEczVeuGexQLoHDIso6NlFrHy2B", wsHandler, errHandler)
	if err != nil {
		fmt.Println(err)
		return
	}
	<-doneC
	
Note*** I am using testnet listending key

**Comment by adshao** [comment]
Hi, `getWsEndpoint()` will return `baseWsTestnetURL` when `binance.UseTestnet = true`, is there any error message?

**Comment by TanjinAlam** [comment]
Yes, it does

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
