### ISSUE TITLE
go-binance needs to stream the partial depth book for simplified depth use cases

### ISSUE THREAD

**Issue by cjamessutton** [adshao/go-binance#38]
Basically, anybody who doesn't need the entire depth book and is only looking for the orders currently surrounding the market price would benefit from this.

[Link to the particular ws endpoint I'm talking about.](https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#partial-book-depth-streams)

**Comment by cjamessutton** [comment]
I'm working on a solution for this right now.

As an aside, what kind of process needs to happen to cut a new release for go dep? I'd love to be able to get at the stopC feature presently in master through dep.

**Comment by cjamessutton** [comment]
Also, hello! This is a GREAT package. Thanks for all the hard work you've obviously put in here.

**Comment by adshao** [comment]
@cjamessutton , I have created tag 1.1.0 based on the master branch, feel free to use it in go dep. Please let me know if there is any issue.

**Comment by cjamessutton** [comment]
Will do. Thanks!

**Comment by adshao** [comment]
close this issue as #39 merged
