### ISSUE TITLE
Can't find a way to call /api/v3/ticker/price with multiple symbols

### ISSUE THREAD

**Issue by blarsy** [adshao/go-binance#380]
I am struggling to find how to gather prices of multiple symbols (not all of them at once, as happens when providing no value to the "symbol" Api parameter). I did not find a related Github issue either.
As per https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#symbol-price-ticker, it is possible on the Binance API's /api/v3/ticker/price endpoint through a "symbol**s**" parameter, but I don't find it in go-binance.

Am I missing something ?

**Comment by adshao** [comment]
> I am struggling to find how to gather prices of multiple symbols (not all of them at once, as happens when providing no value to the "symbol" Api parameter). I did not find a related Github issue either. As per https://github.com/binance/binance-spot-api-docs/blob/master/rest-api.md#symbol-price-ticker, it is possible on the Binance API's /api/v3/ticker/price endpoint through a "symbol**s**" parameter, but I don't find it in go-binance.
> 
> Am I missing something ?

Hi @blarsy , symbols is a new parameter introduced in [spot v3 API](https://binance-docs.github.io/apidocs/spot/en/#symbol-price-ticker), it's appreciated that if you could submit a pr to add it, or I'll add it later.

**Comment by blarsy** [comment]
Ok, will do.
It will be my first PR, but it's never too late to increase one's awesomeness ;-)

**Comment by blarsy** [comment]
Oops, wrong button :-/

**Comment by blarsy** [comment]
#388

**Comment by sleeyax** [comment]
I see the PR has been merged. This issue should therefore be closed.

**Comment by xyq-c-cpp** [comment]
completed, close this.
