### ISSUE TITLE
How to re-run websocket if it down

### ISSUE THREAD

**Issue by Icarus9913** [adshao/go-binance#384]
I found you use for loop to traverse. But once it meet err the whole websokcetTick will down.
In this situation, how can we run it gain?

https://github.com/adshao/go-binance/blob/774259245842dd69ed7731d8ef09a772d9c837b0/v2/futures/websocket.go#L54-L63

**Comment by Icarus9913** [comment]
cc @adshao

**Comment by Icarus9913** [comment]
Can we use `continue` instead of `return` in line 60?

**Comment by Icarus9913** [comment]
This is my err log:
> websokcet get price err(this is custom): `websocket: close 1006 (abnormal closure): unexpected EOF`

**Comment by Icarus9913** [comment]
In another way, we could add one boolean arg to check whether it should continue when it occurs an error.

**Comment by adshao** [comment]
> Can we use `continue` instead of `return` in line 60?

It's impossible to break the loop if we use `continue`. Maybe you can just reconnect websocket from the first place to retry.

**Comment by gurkanguray** [comment]
@Icarus9913 your errHandler function should "handle" the error. If you want to reconnect immediately just reconnect it while error handling. Here is an example function:
```
func errorHandler(symbol string, klineInterval string) func(err error) {
	return func(err error) { // handler function that handles error
		fmt.Println("Error: ", err.Error())
		_, _, err = binance.WsKlineServe(symbol, klineInterval, klineHandler(klineInterval), errorHandler(symbol, klineInterval)) // start the kline websocket connection again with the same interval
		if err != nil {                                                                                                            // if there is an error on reconnecting (I suggest you to check your internet connection first and binance api/server status here)
			fmt.Println(err.Error())
			return
		}
	}
}
```

**Comment by rodrigo-brito** [comment]
I used it with a channel wrapper, when it disconnects I use a backoff retry:
https://github.com/rodrigo-brito/ninjabot/blob/main/exchange/binance.go#L470-L514

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
