### ISSUE TITLE
Update order struct

### ISSUE THREAD

**Issue by syzygy800** [adshao/go-binance#397]
It seems that Binance added two more attributes to their Order regarding their built-in strategies.
I notices it with the "grid bot" strategy. I am testing it right now with "[nefertiti](https://github.com/svanas/nefertiti)" although I have to wait till a order gets filled.
Was planing on doing a PR **if it works as expected**, however if you guys are planing on adding it or if you already have done so then don't mind me :-)

https://github.com/adshao/go-binance/compare/master...syzygy800:go-binance:feat/UpdateBinanceOrder

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
