### ISSUE TITLE
<APIError> code=-1013, msg=Filter failure: MIN_NOTIONAL

### ISSUE THREAD

**Issue by krasi-georgiev** [adshao/go-binance#426]
This error happens when trying to convert small amounts.

I imagine this limit is set on the binance API, but I can't see how to disable it.

Any ideas if this can be disabled or some workaround?

**Comment by f0o** [comment]
You cant, this is Binance's API Backend telling you that you're not meeting the requirements.

https://binance-docs.github.io/apidocs/spot/en/#filters

**Comment by krasi-georgiev** [comment]
Thanks
