### ISSUE TITLE
failed to WebSocket dial: unsupported permessage-deflate parameter: "server_max_window_bits=15"

### ISSUE THREAD

**Issue by guotie** [adshao/go-binance#430]
failed to WebSocket dial: unsupported permessage-deflate parameter: "server_max_window_bits=15"

perp depth ws

**Comment by NNagato** [comment]
what version do you use? i got the same issue with version 2.3.2 but fixed when using the latest version

**Comment by guotie** [comment]
v2.3.8

**Comment by guotie** [comment]
when I upgrade to v2.3.9, the problem still exist.

**Comment by guotie** [comment]
https://github.com/nhooyr/websocket/issues/351

**Comment by kunsonx** [comment]
Check on this library: https://github.com/crypto-zero/go-binance

**Comment by adshao** [comment]
Could you please try with the master branch, let me know if the issue is not fixed, thanks.
