### ISSUE TITLE
Cannot use web-sockets with a proxied connection

### ISSUE THREAD

**Issue by nikhilsaraf** [adshao/go-binance#438]
I am using a `NewProxiedClient` with an http proxy running on my remote server.

It is trying to do the web-socket handshake with binance without going through the proxy.

I temporarily patched this to return the proxy address in the Dialer (not sure if this was done correctly) but now after this i get a different error -- I get an "Access violation". 

The expectation is that if I use a `NewProxiedClient` that i don't need to do anything else and it should just work even for the web-socket handshake.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
