### ISSUE TITLE
Supporting additional futures data

### ISSUE THREAD

**Issue by tanakachitsamba** [adshao/go-binance#440]
I was wondering if there's any chance you could add support for extra futures data? It would be super helpful to be able to access openInterest, openInterestHist, topLongShortAccountRatio, topLongShortPositionRatio, globalLongShortAccountRatio, takerLongShortRatio, and lvtKlines data. As these are probably some of the only few endpoints for futures not supported by the library, It would be a great addition.

**Comment by adshao** [comment]
> 

Is there any binance API supporting these features?

**Comment by zenithyr** [comment]
> > 
> 
> Is there any binance API supporting these features?

I guess he was referring to here [top trader](https://binance-docs.github.io/apidocs/futures/en/#top-trader-long-short-ratio-accounts)

the library already has openInterest & openInterestHist but not the others.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
