### ISSUE TITLE
Feature, network Improvements.

### ISSUE THREAD

**Issue by 0xF7A4C6** [adshao/go-binance#466]
everything was here ;p

https://github.com/dgrr/fastws
https://github.com/valyala/fasthttp

**Comment by rickstaa** [comment]
I agree, fastHTTP support would be wonderful!

**Comment by rickstaa** [comment]
Duplicate of https://github.com/adshao/go-binance/issues/307.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
