### ISSUE TITLE
call and handle WsAllMarketsStatServe

### ISSUE THREAD

**Issue by donfrigo** [adshao/go-binance#48]
Hello,

I am trying to implement the WsAllMarketsStatServe function, but using your example code as a basis, I am constantly running into an error. Could you please help me? The error message is the following: 

> cannot use wsAllMarketsStatHandler (type func(*binance.WsAllMarketsStatEvent)) as type binance.WsAllMarketsStatHandler in argument to binance.WsAllMarketsStatServe

And below is my code:

```
wsAllMarketsStatHandler := func(event *binance.WsAllMarketsStatEvent) {
		fmt.Println(event)
	}
	errHandler := func(err error) {
		fmt.Println(err)
	}
	doneC, _, err := binance.WsAllMarketsStatServe(wsAllMarketsStatHandler, errHandler)
	if err != nil {
		fmt.Println(err)
		return
	}
	<-doneC
```

Thank you!

**Comment by adshao** [comment]
could you please try remove `*` from event since it is an alias to slice

```
wsAllMarketsStatHandler := func(event binance.WsAllMarketsStatEvent) {
	fmt.Println(event)
}
```

**Comment by donfrigo** [comment]
Thank you :)

**Comment by adshao** [comment]
close as resolved
