### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by tsuz** [adshao/go-binance#49]
Hi, v1.1.1 seems to be out of date with master from seeing the [diff](https://github.com/adshao/go-binance/compare/1.1.1...6cf0e802b22a56ff09523536cf27fbb666180a98)

I'm using this commit ID as revision in Gopkg.toml because v1.1.1 doesn't support `binance.NewOrderRespTypeFULL` for example.

Could we tag another release?

**Comment by adshao** [comment]
hi @tsuz , tag 1.1.2 created, let me know if there is any problem.

**Comment by tsuz** [comment]
@adshao Great! Thank you!
