### ISSUE TITLE
Encounter "invalid newOrderRespType" while testing NewCreateOrderService on FutureNet

### ISSUE THREAD

**Issue by ChaShanLiu0830** [adshao/go-binance#491]
While I'm testing the example code  on [testnet.binancefuture.com/](url)
`order, err := client.NewCreateOrderService().Symbol("BNBETH").
        Side(binance.SideTypeBuy).Type(binance.OrderTypeLimit).
        TimeInForce(binance.TimeInForceTypeGTC).Quantity("5").
        Price("0.0030000").Do(context. Background())`

I received the error  `<APIError> code=-1136, msg=Invalid newOrderRespType`

To resolve the issue, I added the line `NewOrderResponseType(binance_futures.NewOrderRespTypeRESULT)` to the code and it works. 
Therefore, I kindly request adding `NewOrderResponseType` to the example code provided in the documentation for the benefit of Binance Futures Testnet users. 

Best regards.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue
