### ISSUE TITLE
Missing `commissionRates` in `GET /api/v3/account`

### ISSUE THREAD

**Issue by MartinTheCzechGuy** [adshao/go-binance#492]
Current response from `GET /api/v3/account` is ignoring the `commissionRates ` object from the response. Would be nice to add it.

`{
  "makerCommission": 15,
  "takerCommission": 15,
  "buyerCommission": 0,
  "sellerCommission": 0,
  "commissionRates": {
    "maker": "0.00150000",
    "taker": "0.00150000",
    "buyer": "0.00000000",
    "seller": "0.00000000"
  },
  "canTrade": true,
  "canWithdraw": true,
  "canDeposit": true,
  "brokered":false,
  "requireSelfTradePrevention": false,
  "updateTime": 123456789,
  "accountType": "SPOT",
  "balances": [
    {
      "asset": "BTC",
      "free": "4723846.89208129",
      "locked": "0.00000000"
    },
    {
      "asset": "LTC",
      "free": "4763368.68006011",
      "locked": "0.00000000"
    }
  ],
    "permissions": [
    "SPOT"
  ]
}`

**Comment by xyq-c-cpp** [comment]
completed, close this.
