### ISSUE TITLE
Single market and all Markets statistics streams

### ISSUE THREAD

**Issue by sazor** [adshao/go-binance#5]
Hi, I found two useful websocket endpoints which aren't implemented in this client.

- 24hr Ticker statistics for a single symbol pushed every second
- 24hr Ticker statistics for all symbols in an array pushed every second

Here is a link to documentation: https://github.com/binance-exchange/binance-official-api-docs/blob/master/web-socket-streams.md#individual-symbol-ticker-streams .
I've implemented it by myself and made pr #4 . Could you please review it?

**Comment by adshao** [comment]
Thanks,  #4 was merged.
