### ISSUE TITLE
Get all SymbolTickers without providing a symbol or []symbols

### ISSUE THREAD

**Issue by csidi90** [adshao/go-binance#501]
Is there any way of retrieving all Symboltickers without specifying a symbol or symbols array to the ListSymbolTickerService?

This is possible in the node, binance and python implementation of the binance API, could not find it in this one tho. The docs dont spit out anything when searching for SymbolTicker either.

**Comment by xyq-c-cpp** [comment]
the feature has been implemented, close this issue.
