### ISSUE TITLE
Futures Client: Constant listenKeyExpired

### ISSUE THREAD

**Issue by JackG-eth** [adshao/go-binance#510]
This is with the futures client.
WsUserDataServe function err handler returns:

2023/08/30 20:28:39 Error unmarshal. {"e": "listenKeyExpired","E": "1693427319838","listenKey": "KEY"}
2023/08/30 20:28:39 Received error: json: cannot unmarshal string into Go struct field WsUserDataEvent.E of type int64

Receive the above message every 30sec-5mins

listen keys should last 60 minutes and can be permanently extended. Any ideas?

**Comment by JackG-eth** [comment]
@adshao Have you seen this error before? I ran my program for 3 hours and about 100 new keys were needed.

**Comment by xyq-c-cpp** [comment]
had fixed this issue, close this.
