### ISSUE TITLE
<APIError> code=-1106, msg=Parameter 'reduceonly' sent when not required.

### ISSUE THREAD

**Issue by csquan** [adshao/go-binance#521]
I had met error:<APIError> code=-1106, msg=Parameter 'reduceonly' sent when not required.
what happened?reduceonly has set false.

**Comment by xyq-c-cpp** [comment]
reduceonly's default value is false, i think you don't need to set it.

**Comment by xyq-c-cpp** [comment]
when your requests exactly need you to set 'reduceonly', you can set it.

**Comment by xyq-c-cpp** [comment]
No response for a long time, close this issue.
