### ISSUE TITLE
how to keep listenKey alive?

### ISSUE THREAD

**Issue by csquan** [adshao/go-binance#522]
follow test code:
client.NewKeepaliveUserStreamService().ListenKey(listenKey).Do(newContext()),
I have few questions. 
how long is the listenKey valid?

**Comment by ldt116** [comment]
Binance document https://binance-docs.github.io/apidocs/futures/en/#user-data-streams already mentioned that.

> A User Data Stream listenKey is valid for 60 minutes after creation.
> Doing a PUT on a listenKey will extend its validity for 60 minutes

**Comment by xyq-c-cpp** [comment]
completed, close this.
