### ISSUE TITLE
something wrong happened when I get account asset?

### ISSUE THREAD

**Issue by csquan** [adshao/go-binance#535]
for example,I use code:
	client := binance.NewClient(apiKey, apiSecret)
	client.SetApiEndpoint(types.Base_binance_url)

	ret, err := client.NewGetAccountService().Do(context.Background())
to get balance,it return like this:{free:xxx,locked:xxx},I use free to get the balance.
but something very weired happen,when I use the method to get balance on 05:00,it show balance 5000+,
when I do it again on 10:00,it show 9000+.
this things happend only once since I used.
I do not know how?

**Comment by csquan** [comment]
maybe free is different,so any other method to get balance?

**Comment by AndreyMashukov** [comment]
Take a look https://github.com/AndreyMashukov/go-crypto-bot , use WS instead of http

**Comment by AndreyMashukov** [comment]
@csquan
