### ISSUE TITLE
Please do a new release

### ISSUE THREAD

**Issue by sloba-byte** [adshao/go-binance#547]
Hi,

I see some fixes have been integrated - however latest release is from Avg 4 2023, a long time ago.

@adshao is it possible you do a new tag for a release?

Thanks!

**Comment by dlisovsky** [comment]
Hey @adshao - yeah please release new version as there was an issue I got using the futures client
<img width="799" alt="image" src="https://github.com/adshao/go-binance/assets/4610433/2a7c7ffb-fb56-4931-8fbc-7b1c86ce098d">
it's updated in the Github but the release 2.4.5 has an issue.

**Comment by adshao** [comment]
Hi, v3.0.0 has been released, let me know if there is any problem.

**Comment by dlisovsky** [comment]
Thank you, @adshao, for such a quick release!

**Comment by adshao** [comment]
> Hey @adshao - could you please let me know how to upgrade to new version? As it seems you did a tag 3.0.1 but GO says there is no release for version 3.

Hi, could you try to use `v2.5.0` instead?

**Comment by dlisovsky** [comment]
Hey @adshao  - `v2.5.0` works for me, thank you!

BTW, do you have an example of how to handle the futures user data WSS? I can see the code, but not sure how to handle it? I tried to do myself but got the issues with connection retry and multiple instances of the connection after the retries. If you can share your best solution, I would be much appreciated.

Thanks in advance!

**Comment by adshao** [comment]
> Hey @adshao - `v2.5.0` works for me, thank you!
> 
> BTW, do you have an example of how to handle the futures user data WSS? I can see the code, but not sure how to handle it? I tried to do myself but got the issues with connection retry and multiple instances of the connection after the retries. If you can share your best solution, I would be much appreciated.
> 
> Thanks in advance!

Hi, you could refer to [the example](https://github.com/adshao/go-binance?tab=readme-ov-file#websocket) of spot and change the package to futures.

**Comment by dlisovsky** [comment]
Hi @adshao - thank you for your reply! 

1. Does it handle the WSS reconnection?

2. How to keep alive the listen key? I can see there is a method, but it seems I need a separate goroutine to keep this triggering every 30 mins. Can you please confirm this?

**Comment by adshao** [comment]
> Hi @adshao - thank you for your reply!
> 
> 1. Does it handle the WSS reconnection?
> 2. How to keep alive the listen key? I can see there is a method, but it seems I need a separate goroutine to keep this triggering every 30 mins. Can you please confirm this?

Hi @dlisovsky ,

1. Yes, I think you should put it in an infinite loop to reconnect automatically.
2. Yes, this project is just a SDK for binance API, we don't handle the specific logic for each API. For your question, I think it's correct to add a goroutine to refresh the listen key. If you have any problem about binance API, it would be better to discuss it in the telegram group of binance developers.

**Comment by dlisovsky** [comment]
Hi @adshao  - yeah I understand it's an SKD and you did a great job!
I thought you may have an example with user data WSS that has all the code to keep the listen key alive and also manages the retries, just in case. That would be much appreciated.
