### ISSUE TITLE
Support for ed25519 secret/signing

### ISSUE THREAD

**Issue by matiboy** [adshao/go-binance#559]
Hi,

Is `ed25519` secret supported?
Or only HMAC? (seems to be only HMAC)

Thanks!

**Comment by xyq-c-cpp** [comment]
yeah, it only supports HMAC. it is great if you could open a PR. @matiboy

**Comment by f0o** [comment]
Considering @xyq-c-cpp closed the original https://github.com/adshao/go-binance/issues/459 issue regarding this without any sensible comment I assume that there is no interest in supporting this.

If you hit Auth issues you will have to disable the `Default Security Controls` unfortunately.

Or switch lib.

**Comment by xyq-c-cpp** [comment]
thanks for your concern, it's implement in last PR.
