### ISSUE TITLE
how to close a market position

### ISSUE THREAD

**Issue by vadinabronin** [adshao/go-binance#580]
very poor list of examples, terrible. without examples, the practical meaning of this library simply tends to zero, so write how I can close the entire position that I have open, 

err := client.ClosePosition().Symbol("DOGEUSDT").Do(context.Background() - it doesn’t work at all

**Comment by xyq-c-cpp** [comment]
It is implemented by users of this package in my opinion. You can use the basic interface provided here to implement this tool interface.
How to implement this? you can get a target position by account interface, and then create an order with target quantities and target price which is needed in LIMIT order type.

**Comment by vadinabronin** [comment]
```res, err := c.NewGetAccountService().Do(context.Background())
        if err != nil {
            return err
        }
        pos := res.Positions``` - it doesn't work at all, it gives zeros everywhere in the positions, it doesn't display anything

**Comment by xyq-c-cpp** [comment]
what's your code?
