### ISSUE TITLE
We need WebSocketAPI !

### ISSUE THREAD

**Issue by DYkgr123** [adshao/go-binance#584]
We need WebSocketAPI ! >wss://ws-fapi.binance.com/ws-fapi/v1  thanks 😄

**Comment by xyq-c-cpp** [comment]
it's great if you can open a PR to implement this.

**Comment by DYkgr123** [comment]
> it's great if you can open a PR to implement this. @DYkgr123 

ok，I'll try

**Comment by xyq-c-cpp** [comment]
> > it's great if you can open a PR to implement this. @DYkgr123
> 
> ok，I'll try

Hello, do you still do for this?

**Comment by alexQi** [comment]
If no one does it in two weeks, I'll do it.

**Comment by xyq-c-cpp** [comment]
> If no one does it in two weeks, I'll do it. I've been a little busy for days
Okay, happy to see that and wait for your PR. @alexQi

**Comment by xyq-c-cpp** [comment]
had implemented and merged.
