### ISSUE TITLE
Request upgrade NewGetPositionRiskService V2 => V3

### ISSUE THREAD

**Issue by yanweidong** [adshao/go-binance#602]
/fapi/v2/positionRisk upgrade to /fapi/v3/positionRisk

**Comment by xyq-c-cpp** [comment]
okay, thanks for your feedback

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
