### ISSUE TITLE
how to implement OTOCO

### ISSUE THREAD

**Issue by MushiTheMoshi** [adshao/go-binance#611]
Hi there,

Thanks for the hard work done here, greatly appreciated!

Looking to implement an OTOCO order in futures api, as per read the doc is not implemented in the same, was wondering then how to implement a take-profit and stop-loss order that auto close the other when one meet condition?

Am I doing something wrong, or this is an unsupported thing. Googled a bit and seems that when quantity is the same in position and orders the expected behavior is achieved , which is not the case here, any help is much appreciated...

this is my code:
```
position_market, err_pos := client.NewCreateOrderService().
        Symbol(TICKER).
        Side(futures.SideTypeBuy).
        PositionSide(futures.PositionSideTypeLong).
        Type(futures.OrderTypeMarket).
        Quantity("0.03").
        WorkingType(futures.WorkingTypeMarkPrice).
        Do(context.Background())

  position_tp, err_tp := client.NewCreateOrderService().
	  Symbol(TICKER).
          Side(futures.SideTypeBuy).
          PositionSide(futures.PositionSideTypeLong).
	  Type(futures.OrderTypeTakeProfitMarket).
	  TimeInForce(futures.TimeInForceTypeGTC).
	  StopPrice(TP).
	  WorkingType(futures.WorkingTypeMarkPrice).
	  Quantity("0.03").
	  Do(context.Background())
  
  position_sl, err_sl := client.NewCreateOrderService().
	  Symbol(TICKER).
	  Side(TYPE_SIDE(SIDE != "LONG")).
          PositionSide(futures.PositionSideTypeLong).
	  Type(futures.OrderTypeTakeProfitMarket).
	  TimeInForce(futures.TimeInForceTypeGTC).
	  Quantity("0.03").
	  StopPrice(SL).
	  WorkingType(futures.WorkingTypeMarkPrice).
	  Do(context.Background())
  ```
  

Regards,
Julio

**Comment by xyq-c-cpp** [comment]
I think your implementation is right, but you should do some tests to verify it with some real trade. @MushiTheMoshi

**Comment by MushiTheMoshi** [comment]
ok, thanks for confirming, will give it a try...

**Comment by MushiTheMoshi** [comment]
seems ok, thx
