### ISSUE TITLE
TRADE_LITE user-data WS event

### ISSUE THREAD

**Issue by vlw** [adshao/go-binance#612]
Binance introduced new event in userdata WS: https://www.binance.com/en/support/announcement/introducing-trade-lite-for-usd%E2%93%A2-m-futures-websocket-2024-09-03-f2809259702b46f7abdc9c97b977908f

https://developers.binance.com/docs/derivatives/usds-margined-futures/user-data-streams/Event-Trade-Lite

it's incompatible with our futures.WsUserDataEvent

```
type WsUserDataEvent struct {
    Event               UserDataEventType     `json:"e"`
    Time                int64                 `json:"E"`
    CrossWalletBalance  string                `json:"cw"`
    MarginCallPositions []WsPosition          `json:"p"`
    TransactionTime     int64                 `json:"T"`
    AccountUpdate       WsAccountUpdate       `json:"a"`
    OrderTradeUpdate    WsOrderTradeUpdate    `json:"o"`
    AccountConfigUpdate WsAccountConfigUpdate `json:"ac"`
}
```

json: cannot unmarshal string into Go struct field .p of type []futures.WsPosition

**Comment by vlw** [comment]
Previously all WS responses were compatible with each other, looks like a malformed API on Binance's part

**Comment by xyq-c-cpp** [comment]
> Previously all WS responses were compatible with each other, looks like a malformed API on Binance's part

does that problem still occur? @vlw

**Comment by vlw** [comment]
> does that problem still occur?

yes

**Comment by xyq-c-cpp** [comment]
> > does that problem still occur?
> 
> yes

okay, it's great if you can check what exactly happens and open a PR to fix this issue, if you have free time. @vlw
