### ISSUE TITLE
AmountToLotSize works incorrect

### ISSUE THREAD

**Issue by ramilexe** [adshao/go-binance#615]
There is `MEWUSDT` token on Binance futures with following parameters:
```json
"pricePrecision": 7,
"filters": [
{
    "filterType": "PRICE_FILTER",
    "minPrice": "0.0000010",
    "tickSize": "0.0000010",
    "maxPrice": "200"
}]
```

When I call `AmountToLotSize(0.0000010, 7, 0.003923153000000002)` I get `0.0039229` but expected value is `0.003923`. Because of that I get error `<APIError> code=-4014, msg=Price not increased by tick size.`

**Comment by xyq-c-cpp** [comment]
thanks for your feedback, it is no longer applicable at present, I saw. @ramilexe  I recommend that you follow tickSize completely, not pricePrecision. I would fix this function later.

**Comment by ramilexe** [comment]
@xyq-c-cpp I replaced it with following function:

```go
// RoundPriceToTickSize rounds the price to the nearest tick size
func RoundPriceToTickSize(price, tickSize float64) float64 {
	if tickSize == 0 {
		return price // To avoid division by zero
	}
	// Calculate the factor by which to multiply and divide the price to conform to the tick size.
	factor := 1 / tickSize

	// Round the price to the nearest tick size.
	roundedPrice := math.Round(price*factor) / factor

	return roundedPrice
}
```

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by ramilexe** [comment]
@xyq-c-cpp @adshao in which PR it was fixed?

**Comment by ramilexe** [comment]
code is still not fixed https://github.com/adshao/go-binance/blob/master/v2/common/helpers.go#L10
