### ISSUE TITLE
[feature] mock support 

### ISSUE THREAD

**Issue by MushiTheMoshi** [adshao/go-binance#622]
Hi ,

Is there a way to implement mocking out of the box?  testing hits rate limit quite often and you get banned from time to time. Do you know how can I implement mocking to avoid this in case is not supported yet?

Regards,
Julio

**Comment by xyq-c-cpp** [comment]
sorry, don't know what you mean. what's the mocking out of the box? current the api request speed is controled by users. @MushiTheMoshi

**Comment by MushiTheMoshi** [comment]
sorry, I meant how can I mock http responses...

**Comment by xyq-c-cpp** [comment]
sorry, don't know about mock. you can implement this to push a PR if you know how to do it. @MushiTheMoshi

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
