### ISSUE TITLE
binance.us

### ISSUE THREAD

**Issue by SamHobbsOrg** [adshao/go-binance#629]
I have been informed that this library does not support `binance.us` for those of us in the USA. I request that support be added.

I am an experienced programmer familiar with many languages but I am not yet familiar with Go. I am also not familiar with the Binance API. I will try to add the support if I need to but it will take time. If someone else can do it then that will help.

One thing that is not clear is whether the APIs for `binance.us` and `binance.com` are significantly different. If I attempt to implement the support myself then any guidance is appreciated.

**Comment by xyq-c-cpp** [comment]
There should not be this restriction, but it is uncertain whether the binance.us API is applicable. You can test whether the binance.us API is currently being used in this library. You should only need to set the URL when using the library.
@SamHobbsOrg

**Comment by xyq-c-cpp** [comment]
for example, `v2/client.go:BaseAPIMainURL` can be set. @SamHobbsOrg

**Comment by SamHobbsOrg** [comment]
Thank you. I will try doing a test to determine if it is that simple.
