### ISSUE TITLE
Use built-in `json` package instead of `json-iterator`

### ISSUE THREAD

**Issue by khiemdoan** [adshao/go-binance#638]
The `json-iterator` package is no longer maintained; its last update was two years ago (Sep 16, 2022)

There are numerous issues related to performance and crashes, such as:
- https://github.com/modern-go/reflect2/issues/31
- https://github.com/json-iterator/go/issues/671
- https://github.com/json-iterator/go/issues/494
- https://github.com/json-iterator/go/issues/658

Some projects have removed it, including:
- https://github.com/kubernetes/kubernetes/pull/105030
- https://github.com/etcd-io/etcd/pull/13439

I think it’s better to use the built-in json package for the best compatibility.

**Comment by xyq-c-cpp** [comment]
thanks for your feedback, we would fix this later. @khiemdoan
