### ISSUE TITLE
Add Modify Multiple Orders Endpoint - USD-M Futures

### ISSUE THREAD

**Issue by khanbekov** [adshao/go-binance#647]
Hello,

I noticed that the Modify Multiple Orders endpoint, described in the Binance API documentation ([link](https://developers.binance.com/docs/derivatives/usds-margined-futures/trade/rest-api/Modify-Multiple-Orders)), is not currently implemented in this library.

Adding support for this functionality would be very helpful for batch order modifications. I encountered the need for this method while working on a system I'm developing.

The library already includes methods for placing and canceling multiple orders, so the absence of this endpoint seems like an oversight.

I plan to work on a PR to implement this feature in the near future.

**Comment by xyq-c-cpp** [comment]
okay, that's fine if you can push a PR to implement this feature. thanks so much. @khanbekov

**Comment by xyq-c-cpp** [comment]
had merged, close this.
