### ISSUE TITLE
DepositAddress API missing

### ISSUE THREAD

**Issue by krishnagrep** [adshao/go-binance#67]
I guess this endpoint is missing
https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md#deposit-address-user_data
Could you please also include this one
@jeremyhahn @sazor

**Comment by krishnagrep** [comment]
ExchangeInfoService is also giving JSON parse error
`json: cannot unmarshal number into Go value of type string`

**Comment by riaan53** [comment]
Hi @krishnagrep , For the json unmarshal error use the latest master of this lib. It has been fix but not yet release.

**Comment by krishnagrep** [comment]
@adshao No It's fine , I updated my local repo as suggested by @riaan53 .

**Comment by adshao** [comment]
@krishnagrep  thanks. For the deposit addresses API, you can submit a pull request for that.

**Comment by krishnagrep** [comment]
@adshao Will submit a pull request over the weekend.
