### ISSUE TITLE
How to convert Binance timestamp to datetime?

### ISSUE THREAD

**Issue by stanhordiyenko** [adshao/go-binance#73]
Hi, could you help me with Binance timestamp conversion to Time in Golang? Cheers.

`tm := time.Unix(order.Time, 0)` doesn't work and returns some time in the far far future.

**Comment by adshao** [comment]
> All time and timestamp related fields are in milliseconds.

You should use `order.Time / 1000`

**Comment by stanhordiyenko** [comment]
Thank you, @adshao It works.
