### ISSUE TITLE
Cannot unmarshal number into Go value of type string

### ISSUE THREAD

**Issue by kelf47** [adshao/go-binance#75]
I'm getting this error on NewExchangeInfoService.Do 
 I guess binance is returning an integer defined as string.
https://github.com/adshao/go-binance/blob/e9a4ac01ca4814807bd4fb573da2129564cb23b3/exchange_info_service.go#L25

**Comment by adshao** [comment]
Hi @kelf47 Could you submit a pr for it?

**Comment by kelf47** [comment]
Hi! Sorry I had an old version of go-binance code. With the new 1.2.0 release all is working properly. Thx!
