### ISSUE TITLE
Stop websocket within handler?

### ISSUE THREAD

**Issue by TheLetterJ** [adshao/go-binance#77]
Is there a way to stop/pause the websocket stream from within the handler? I see the use of a timer and stopC in the WsDepthServe example in the readme, but that is not what I'm looking for. What would be the elegant way to stop the stream while its running without the use of a timer? Thanks!

**Comment by adshao** [comment]
Hi @TheLetterJ ,  I think we need to refactor wsServe to pass stopC to handler in https://github.com/adshao/go-binance/blob/master/websocket.go#L54, could you please submit a pr for that? or I'll implement it later. Thanks.

**Comment by TheLetterJ** [comment]
So I was able to accomplish this by declaring doneC before everything:

`doneC := make(chan struct{})`

Then I used

`doneC <- struct{}{}`

inside the handler. It seemed to work fine, but I'm not sure if this is ideal.
