### ISSUE TITLE
GetWithdrawFeeService is not working

### ISSUE THREAD

**Issue by halink0803** [adshao/go-binance#78]
I tried to use get withdraw fee using GetWithdrawFeeService but is is not working. It returns binance.APIError{Code: 0, Msg:""}.

I checked with [official documentation](https://github.com/binance-exchange/binance-official-api-docs/blob/master/wapi-api.md), and it seems the does not have /wapi/v3/withdrawFee.html anymore. Instead, they have /wapi/v3/assetDetail.html, which they include withdrawFee there.

It would be great if you can implement assetDetail method to get assetDetail from Binance api. 

Best regards,

**Comment by adshao** [comment]
hi @halink0803 , Could you please submit a pr for that?
