### ISSUE TITLE
Does the WsKlineServe return the last 500 candles?

### ISSUE THREAD

**Issue by loganbfisher** [adshao/go-binance#81]
I am rewriting a project in go from javascript and the other library I used for websockets and candle updates provided me with the last 500 candles for a coin and then would provide updates to that candle.  Does this service also do that?  If not can you point me in the right direction?

**Comment by adshao** [comment]
Hi @loganbfisher , WsKlineServe just receives messages from binance server, maybe you need KlinesService to get the last 500 candles before serving websocket: https://github.com/adshao/go-binance/blob/master/kline_service.go#L9

**Comment by loganbfisher** [comment]
Ah nice ok I really appreciate the fast response!  I will check that out!

**Comment by xyq-c-cpp** [comment]
completed, close it.
