### ISSUE TITLE
[Feature Request] Support margin api

### ISSUE THREAD

**Issue by qmn1711** [adshao/go-binance#87]
Binance has released margin api: https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md

Please add this to the SDK, thank you @adshao!

**Comment by adshao** [comment]
Hi @qmn1711 , thanks for the update, I'll add margin soon.

**Comment by adshao** [comment]
@qmn1711 margin api is in developing on branch feature/margin-trade: https://github.com/adshao/go-binance/tree/feature/margin-trade, will be merged into master as soon as it is finished

**Comment by qmn1711** [comment]
it's great, also thanks for your v3 APIs updating!

**Comment by adshao** [comment]
resolved as #93 merged
