### ISSUE TITLE
[Feature Request] Need Websocket AutoReconnect

### ISSUE THREAD

**Issue by skanger** [adshao/go-binance#89]
It may be helpful for people who has unstable network .

**Comment by adshao** [comment]
hi @skanger , could you please describe your issue in more detail? for ws, you can put it in an infinite loop to reconnect.

**Comment by skanger** [comment]
can you put the code on READ.ME?
I usually used  Client to do reconnect.
because of this repo used "event mode", I don't know how to write "infinite loop" to reconnect.

BLOW IS CHINESE TRANSLATE:
能写一下具体的用法吗？
因为我看你用的是事件模型+handler组合，一组 有 messageHandler和errorHandle, 跟js的设计很像，但是我一般用client来做，假设我订阅10个symbol，那么就有10组handler，假设某一个symbol掉了，client没有保存哪个symbol掉了，就无法及时重新订阅了。
我尝试过在 errorHandle里面自己发起重新订阅，但是没有走通。

**Comment by adshao** [comment]
@skanger 能把你的错误信息发一下吗？具体是哪一行推出的？

**Comment by skanger** [comment]
```
func BinanceWsPush(symbol []string) {
	for _, v := range symbol {
                WsSub(v)
        }
}

func WsSub() {
        var err error
	wsKlineHandler := func(event *binance.WsKlineEvent) {
		if event.Time > 0 {
		
		    // do something
		}

	}
	errHandler := func(err error) {
		beego.Error(symbol, "websocket disconnected")
		//WsSub(symbol)
	}
	_, _, err = binance.WsKlineServe(symbol, "1m", wsKlineHandler, errHandler)
	if err != nil {
		panic(err)
		return
	}

}

```
我没有捕捉这个error，因为我要的效果是一担某个symbol断开了，立马重新订阅，保证数据不断。
能贴一下你说的死循环不断开是什么样子吗？

**Comment by skanger** [comment]
报错error内容如下
```
2019/08/09 12:33:00.112 [E] [binance.go:134]  etcusdt websocket: close 1006 (abnormal closure): unexpected EOF websocket 已断开 
2019/08/09 12:33:00.112 [E] [binance.go:134]  etcusdt write tcp 172.21.17.186:49490->54.65.181.48:9443: i/o timeout websocket 已断开 
2019/08/09 12:33:00.124 [E] [binance.go:134]  trxusdt websocket: close 1006 (abnormal closure): unexpected EOF websocket 已断开 
2019/08/09 12:33:00.124 [E] [binance.go:134]  trxusdt write tcp 172.21.17.186:39908->54.178.167.48:9443: i/o timeout websocket 已断开 
2019/08/09 12:33:00.202 [E] [binance.go:134]  adausdt websocket: close 1006 (abnormal closure): unexpected EOF websocket 已断开 
2019/08/09 12:33:00.202 [E] [binance.go:134]  adausdt write tcp 172.21.17.186:46502->54.64.145.25:9443: i/o timeout websocket 已断开 
2019/08/09 12:33:00.216 [E] [binance.go:134]  xrpusdt websocket: close 1006 (abnormal closure): unexpected EOF websocket 已断开 
2019/08/09 12:33:00.217 [E] [binance.go:134]  xrpusdt write tcp 172.21.17.186:55334->52.69.33.232:9443: i/o timeout websocket 已断
```

**Comment by adshao** [comment]
hi @skanger , binance.WsKlineServe 这个方法返回的第一个值是channel，你可以监听这个channel来实现重新连接：
```
for {
    doneC, _, err := binance.WsKlineServe(symbol, "1m", wsKlineHandler, errHandler)
    if err != nil {
        panic(err)
    }
    <-doneC
}

```

**Comment by elboletaire** [comment]
I'm facing with this error a lot these days. Shouldn't this error be returned in the `errHandler` function? Or it is an error returned to the `err` var above? I'm a bit confused because I also have a `panic` there, but the error doesn't look as a panic error at all (it doesn't even have the `panic` word prefixing it):

~~~
websocket: close 1006 (abnormal closure): unexpected EOF
write tcp 46.101.93.109:45044->18.177.89.82:9443: i/o timeout
~~~

**Comment by JackG-eth** [comment]
Hey, Did we ever solve this? I'm recieving this error and not having it handled by the errorhandler seems random?
like @elboletaire  mentioned above.
