### ISSUE TITLE
Need margin user data stream

### ISSUE THREAD

**Issue by henrytw** [adshao/go-binance#95]
Could you add this feature?
Thank you.

**Comment by adshao** [comment]
hi @henrytw , could you please give me the link of this API?

**Comment by henrytw** [comment]
https://github.com/binance-exchange/binance-official-api-docs/blob/master/margin-api.md
Start user data stream: POST /sapi/v1/userDataStream
Delete: DELETE  /sapi/v1/userDataStream
Keep: PUT  /sapi/v1/userDataStream

**Comment by adshao** [comment]
thanks @henrytw , just added these API in #96 , please checkout the latest code, and let me know if there is any problems.

**Comment by adshao** [comment]
closed as #96 merged
