### ISSUE TITLE
[Feature Request] Support Futures API

### ISSUE THREAD

**Issue by michakfromparis** [adshao/go-binance#98]
Binance has released the futures API documentation here:
https://binanceapitest.github.io/Binance-Future-API-test-doc/general_info/

**Comment by michakfromparis** [comment]
Being able to retrieve the balance / positions would be a good start.

**Comment by adshao** [comment]
Thanks for the suggestion, I will look into the future API and add future support after that.

**Comment by Algalish** [comment]
@adshao  Hi! Are you working on Futures, and if yes - is there some kind of date, when you think it will be available?
Thx in advance!

**Comment by adshao** [comment]
> @adshao Hi! Are you working on Futures, and if yes - is there some kind of date, when you think it will be available?
> Thx in advance!

Hi @Algalish , Yes, I'm working on it, but there are other issues affect the progress, I think it will be available in next two weeks.

**Comment by adshao** [comment]
Hi @michakfromparis @Algalish , Futures API support is implemented in #104 , which will be merged into master as long as functional testing completes. Feel free to use branch `feature/futures` for testing.

**Comment by Krisa** [comment]
Hi @adshao. Thanks for adding this feature! Were you able to successfully complete the functional testing or is something failing?

**Comment by adshao** [comment]
@Krisa Yes, #104 has beed merged, it would be appreciated if you can help us test this new feature.
